### ISSUE TITLE
lang stanza of dune-package should be the same as in dune-project

### ISSUE THREAD

**Issue by Khady** [ocaml/dune#2216] opened 2019-05-30 05:51 UTC
The `dune-package` file generated during the installation of a package contains a `lang` stanza. The version in this stanza is the version of the dune used to compile the package. But the version of dune might be different from the version specified in `dune-project`.

This is a problem when one wants to downgrade dune in an opam switch. For example if one:

- create a switch with dune 1.9.3 and install devkit
- compile a project
- downgrade dune to 1.8.2 (`opam install dune.1.8.2`)
- try to compile again the same project

Then one will get an error that looks like:

```
File "/home/louis/.opam/a/lib/devkit/dune-package", line 1, characters 11-14:
1 | (lang dune 1.9)
              ^^^
Error: Version 1.9 of dune is not supported.
Supported versions:
- 0.0
- 1.0 to 1.8
```

At this point there is no good solution but to run `opam switch reinstall`.

The dune-project file of devkit looks like this:

```
(lang dune 1.5)
(name devkit)
```

I took devkit as an example, but it is exactly the same thing with any other package using dune as a build system.

**Comment by rgrinberg** [comment] 2019-05-30 07:21
I think this is a duplicate of https://github.com/ocaml/dune/issues/2147

**Closed by rgrinberg** 2019-05-30 07:21 UTC
