### ISSUE TITLE
mdx tests fail on Windows

### ISSUE THREAD

**Issue by anton-trunov** [ocaml/dune#3849] opened 2020-10-04 15:39 UTC
## Expected Behavior

`mdx` tests work

## Actual Behavior

An error:
```
Error: Rule failed to generate the following targets:
- test/typechecker/.mdx/apply.md.corrected
```

## Reproduction

Here is a link to the results produced by GitHub Action: https://github.com/anton-trunov/modal-type-theory/runs/1205640877?check_suite_focus=true. The same `mdx` tests work fine on Ubuntu and macOS. Dependency installation and `dune build` also work on Windows, but running the tests fails.

## Specifications

- Version of `dune` (output of `dune --version`): 2.7.1
- Version of `ocaml` (output of `ocamlc --version`): 4.07.1, 4.08.1, 4.09.1, 4.10.1, 4.11.1
- Operating system (distribution and version): Windows Server 2019 (according to the description [here](https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners))

**Comment by rgrinberg** [comment] 2020-10-04 20:09
@nojb any idea what might be causing this?

**Comment by nojb** [comment] 2020-10-05 09:11
No idea, and the error message does not give much information. I have never used the `mdx` stuff, so I will need to try to reproduce this locally. Am a bit busy at the moment, but will try to do it later today if I have the time.

**Comment by anton-trunov** [comment] 2020-10-05 10:01
Please let me know if I can help in anyway. I can add `--verbose` flag and produce new CI results if you think it could help.

**Comment by nojb** [comment] 2020-10-05 11:23
Before I try to compile `mdx` which has a rather lage number of dependencies, can someone confirm that it is supposed to work on Windows?

**Comment by rgrinberg** [comment] 2020-10-05 17:13
@samoht  @NathanReb is mdx supposed to work on Windows?

**Comment by NathanReb** [comment] 2020-10-05 18:34
I'd certainly like it to work on windows but we didn't put any effort into it recently so it's definitely possible that it doesn't. I'll take a look !

**Comment by emillon** [comment] 2020-11-13 16:10
I just had a look at this one, since it affects mdx's testsuite too (I think it affects all users of the mdx stanza too)

With this stanza:

```
(rule
 (target test-case.t.corrected)
 (deps
  (package mdx)
  (:md test-case.t))
 (action
  (run ocaml-mdx test --output %{target} %{md})))
```

dune complains that the rule did not generate `test-case.t.corrected`. But when we look in the build directory, the file is there.

To give some context, `ocaml-mdx test` executes into `ocaml-mdx-test` with the same arguments (one reason for this split is that `ocaml-mdx-test` is built as bytecode to be able to run toplevel fragments):

https://github.com/realworldocaml/mdx/blob/04bc0925ca0bfc58271504131c7b2cb3510cb1c9/bin/test.ml#L44

The following change in mdx fixes the situation (error handling TBD):

```diff
--- a/bin/test.ml
+++ b/bin/test.ml
@@ -41,7 +41,9 @@ let run (`Setup ()) _ _ _ _ _ _ _ _ _ _ =
   let argv = Array.sub Sys.argv 1 (Array.length Sys.argv - 1) in
   argv.(0) <- cmd;
   Log.debug (fun l -> l "executing %a" Fmt.(Dump.array string) argv);
-  Unix.execvp cmd argv
+  let pid = Unix.create_process cmd argv Unix.stdin Unix.stdout Unix.stderr in
+  let _ = Unix.waitpid [] pid in
+  Stdlib.exit 0
```

I think what's happening is that on windows, execvp is creating a new process and dune does not know about this. But I don't know if that's something that can be fixed in dune.

**Comment by rgrinberg** [comment] 2022-05-23 02:52
@emillon is this still relevant?

**Comment by emillon** [comment] 2022-07-22 14:55
No, it's not. Upgrading mdx to 1.8.0 will solve the issue for dune users.

**Closed by emillon** 2022-07-22 14:55 UTC
Labels: windows, mdx
