### ISSUE TITLE
dune's cache crashes if .cache or .cache/dune is mounted on another device

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/dune#2892] opened 2019-11-19 00:49 UTC
Dune's cache doesn't work if for whatever reason, `~/.cache` or `~/.cache/dune` is mounted on another disk or device than your project or `.opam` for example (when using opam).

In my example I'm trying to use dune's cache to speed up [opam-health-check](https://github.com/kit-ty-kate/opam-health-check) by sharing `~/.cache/dune` across multiple docker executions via a single volume.

The issue can be reproduce as follow:
```
$ export DUNE_CACHE=enabled
$ mkdir -p ~/.cache/dune
$ sudo mount -t tmpfs -o size=1G tmpfs /home/opam/.cache/dune
$ opam install dune.2.0.0+draft2 # or opam pin add --dev dune
[...]
#=== ERROR while compiling dune.2.0.0+draft2 ==================================#
# context     2.0.5 | linux/x86_64 | ocaml-base-compiler.4.06.1 | pinned(git+https://github.com/ocaml/dune.git#bc6bcb4c)
# path        ~/.opam/4.06.1/.opam-switch/build/dune.2.0.0+draft2
# command     ~/.opam/4.06.1/.opam-switch/build/dune.2.0.0+draft2/./dune.exe build -p dune --profile dune-bootstrap -j 71
# exit-code   1
# env-file    ~/.opam/log/dune-3936-0325cb.env
# output-file ~/.opam/log/dune-3936-0325cb.out
### output ###
# Error: link: /home/opam/.cache/dune/db/v2/temp/promoting: Invalid cross-device link
[...]
```

**Comment by diml** [comment] 2019-11-20 14:47
We chatted offline. The issue is that dune hardlinks things between the various build directories and the shared cache. We are thinking of adding an option to do plain copies instead.

**Comment by Chris00** [comment] 2019-11-20 14:56
Isn't it possible to detect when hardlinking fails and, in this case, do simple copies?

**Comment by diml** [comment] 2019-11-20 15:01
The main issue is that if we don't hardlink, it is difficult to know what is used from the shared cache. In particular, trimming becomes complicated. So it seems better to make this behaviour explicit.

**Comment by mefyl** [comment] 2019-11-23 11:29
WIP in https://github.com/mefyl/dune/tree/feature/dune-cache-copy-mode .

**Comment by mefyl** [comment] 2020-03-02 17:04
This was fixed with copy mode, which will be auto-selected if the cache is on another device.

**Closed by mefyl** 2020-03-02 17:04 UTC
Labels: shared-cache
