### ISSUE TITLE
jbuilder install --libdir does not follow its --help specification

### ISSUE THREAD

**Issue by pirbo** [ocaml/dune#250] opened 2017-09-06 14:41 UTC
You can read on `jbuilder install --help`:
```
--libdir=PATH
           Directory where library files are copied, relative to prefix or
           absolute. If --prefix is specified the default is $prefix/lib,
           otherwise it is the output of ocamlfind printconf destdir
```
but the reality seems to be
```
--libdir=PATH
           Directory where library files are copied, relative to prefix or
           absolute. The default is the output of ocamlfind printconf destdir
```
I experimented with `easy-format`:
```
$ OCAMLFIND_DESTDIR=/tmp/anothertest jbuilder install --prefix /tmp/thisisatest
opam-installer easy-format.install
Creating directory /tmp/anothertest/easy-format
_build/install/default/lib/easy-format/META => /tmp/anothertest/easy-format/META
_build/install/default/lib/easy-format/opam => /tmp/anothertest/easy-format/opam
_build/install/default/lib/easy-format/easy_format.cmi => /tmp/anothertest/easy-format/easy_format.cmi
_build/install/default/lib/easy-format/easy_format.cmx => /tmp/anothertest/easy-format/easy_format.cmx
_build/install/default/lib/easy-format/easy_format.cmt => /tmp/anothertest/easy-format/easy_format.cmt
_build/install/default/lib/easy-format/easy_format.cmti => /tmp/anothertest/easy-format/easy_format.cmti
_build/install/default/lib/easy-format/easy_format.mli => /tmp/anothertest/easy-format/easy_format.mli
_build/install/default/lib/easy-format/easy_format.cma => /tmp/anothertest/easy-format/easy_format.cma
_build/install/default/lib/easy-format/easy_format.cmxa => /tmp/anothertest/easy-format/easy_format.cmxa
_build/install/default/lib/easy-format/easy_format.a => /tmp/anothertest/easy-format/easy_format.a
_build/install/default/lib/easy-format/easy_format.cmxs => /tmp/anothertest/easy-format/easy_format.cmxs
_build/install/default/doc/easy-format/README.md => /tmp/thisisatest/doc/easy-format/README.md
_build/install/default/doc/easy-format/LICENSE => /tmp/thisisatest/doc/easy-format/LICENSE
```

**Comment by dra27** [comment] 2017-09-06 15:01
cf. #202, b1e140eef360d1802e926892225afcb904e2078c & cfd43d5282c2d249ea7f23e62edfda11ff8f9f86

It's not entirely clear to me from the thread which is at fault - the behaviour, or the docs. @diml?

**Comment by diml** [comment] 2017-09-06 15:12
It's a bug in the behaviour. If you pass an explicit `--prefix` option, jbuilder shouldn't put files at arbitrary locations in the filesystem.

**Comment by dra27** [comment] 2017-09-06 15:23
@diml - ta, it's on the list (for one or other of us!). It wasn't clear from the thread in #202 if `lib` was allowed to be an exception to that or not!

**Comment by rgrinberg** [comment] 2018-11-06 20:18
Now that dune doesn't use opam-installer, this is now fixed. I could not reproduce the bug.

**Closed by rgrinberg** 2018-11-06 20:18 UTC
