### ISSUE TITLE
js_of_ocaml - javascript_files - no rule found

### ISSUE THREAD

**Issue by nickbetteridge** [ocaml/dune#2064] opened 2019-04-17 10:31 UTC
Not too sure what this relates to, whether it's a dune or opam issue -
dune:1.9.1
opam:2.0.4
dune file:
```
(library
  (name my_lib)
  (public_name my-lib)
  (libraries ezjsonm)
  (js_of_ocaml (javascript_files my.lib.min.js))
  (preprocess (pps js_of_ocaml-ppx))
)
```
```opam pin add my-lib .``` gives:
```### output ###
# [...]
# dune build
# File "lib_js/dune", line 2, characters 0-175:
# 2 | (library
# 3 |   (name my_lib)
# 4 |   (public_name my-lib)
# 5 |   (libraries ezjsonm)
# 6 |   (js_of_ocaml (javascript_files my.lib.min.js))
# 7 |   (preprocess (pps js_of_ocaml-ppx))
# 8 | )
# Error: No rule found for lib_js/my.lib.min.js
# Makefile:4: recipe for target 'build' failed
# make: *** [build] Error 1



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build my-lib 0.0
└─ 
╶─ No changes have been performed
[NOTE] Pinning command successful, but your installed packages may be out of sync.
```
```my.lib.min.js``` is present in lib_js

**Comment by diml** [comment] 2019-04-18 09:05
Did this use to work with older dune versions? I see no occurence of `min.js` in the dune code base. I checked in master and 1.8.2. So I'm not sure this was ever supported. Could you show the full `lib_js/dune` file?

**Comment by nickbetteridge** [comment] 2019-04-18 09:23
That is the full dune file.

```dune build``` works without error and my javascript file ends up in ```_build/default/lib_js``` as specified with ```javascript_files```.

It's just the pinning that goes awry.

Doing a ```dune install``` happily puts the ```my.lib.min.js``` into ```~/.opam/default/lib/....```, so other projects can see the library. Changing the name to something like ```my_lib_min.js``` produces the same error.

Hhhhmmm, not too sure if I tried the pinning before - I have a feeling that I might have and it worked.

**Comment by ejgallego** [comment] 2021-04-28 14:32
Hi @nickbetteridge , I couldn't reproduce with a similar setup in my own jsoo projects; given the age of this issue I'm closing; if still an issue, please reopen with a minimal reproducible example we can look at.

**Closed by ejgallego** 2021-04-28 14:32 UTC
