### ISSUE TITLE
bun tests fail with dune 2.0 due to "aliases must have targets"

### ISSUE THREAD

**Issue by avsm** [ocaml/dune#2912] opened 2019-11-24 07:17 UTC
This used to build with dune<2, so might be a behaviour change that can be guarded behind a `(lang)` flag.

```
#=== ERROR while compiling bun.0.3.3 ==========================================#
1331	# context              2.0.5 | linux/x86_64 | ocaml-variants.4.07.1+afl | pinned(git+https://github.com/yomimono/ocaml-bun.git#ded63582)
1332	# path                 ~/.opam/4.07+afl/.opam-switch/build/bun.0.3.3
1333	# command              ~/.opam/4.07+afl/bin/dune build -p bun -j 71
1334	# exit-code            1
1335	# env-file             ~/.opam/log/bun-35580-a1a23d.env
1336	# output-file          ~/.opam/log/bun-35580-a1a23d.out
1337	### output ###
1338	# File "/home/opam/.opam/4.07+afl/lib/crowbar/crowbar.dune", line 1, characters 0-0:
1339	# Warning: .dune files are ignored since 2.0. Reinstall the library with dune
1340	# >= 2.0 to get rid of this warning and enable support for the subsystem this
1341	# library provides.
1342	# File "test/dune", line 19, characters 19-37:
1343	# 19 |    (with-stdout-to "shorttest-output"
1344	#                         ^^^^^^^^^^^^^^^^^^
1345	# Error: Aliases must not have targets.
```

**Comment by rgrinberg** [comment] 2019-11-24 07:35
I believe this is an intended breaking change. Note that this was a warning in 1.11

**Comment by rgrinberg** [comment] 2020-03-23 23:39
Closing as this was the intended behavior (one of the few breaking changes in dune 2.0).

**Closed by rgrinberg** 2020-03-23 23:39 UTC
