### ISSUE TITLE
Issue building packages on windows: rmdir, Directory not empty

### ISSUE THREAD

**Issue by hhugo** [ocaml/dune#8228] opened 2023-07-18 16:27 UTC
I'm seeing issues on windows using dune 3.9.1.

I've witnessed this behavior in jsoo and zarith CI so far.
- https://github.com/ocaml/Zarith/actions/runs/5589049596/jobs/10216750778?pr=143
- https://github.com/ocsigen/js_of_ocaml/actions/runs/5588550201/jobs/10215512355?pr=1490

The error looks like this:

```
#=== ERROR while compiling sexplib0.v0.16.0 ===================================#
# context     2.0.10 | win32/x86_64 | ocaml.5.0.0 ocaml-option-mingw.1 | git+https://github.com/ocaml/opam-repository.git
# path        D:/a/js_of_ocaml/js_of_ocaml/_opam/.opam-switch/build/sexplib0.v0.16.0
# command     D:\a\js_of_ocaml\js_of_ocaml\_opam\bin\dune.exe build -p sexplib0 -j 2
# exit-code   1
# env-file    D:/.opam/log/sexplib0-5660-51cb9c.env
# output-file D:/.opam/log/sexplib0-5660-51cb9c.out
### output ###
# Error:
# rmdir(C:\Users\runneradmin\AppData\Local\Microsoft\Windows\INetCache\dune\db\temp\dune_80f647_artifacts): Directory not empty
# -> required by
#    _build/default/src/.sexplib0.objs/sexplib0__Sexp_conv_grammar.impl.d
# -> required by
#    _build/default/src/.sexplib0.objs/sexplib0__Sexp_conv_grammar.impl.all-deps
# -> required by
#    _build/default/src/.sexplib0.objs/byte/sexplib0__Sexp_conv_grammar.cmt
# -> required by
#    _build/install/default/lib/sexplib0/sexplib0__Sexp_conv_grammar.cmt
# -> required by _build/default/sexplib0.install
# -> required by alias install
```

## Specifications

- Version of `dune` (output of `dune --version`): 3.9.1 
- Version of `ocaml` (output of `ocamlc --version`): 4.14 and 5.0
- Operating system (distribution and version): windows

**Comment by hhugo** [comment] 2023-07-19 08:45
This issue doesn't seem to exist in dune 3.8.3

**Comment by emillon** [comment] 2023-07-19 13:35
#7371 looks like a promising candidate (given the different semantics of unlinking on Windows), but it seems to be disabled by default.

**Comment by emillon** [comment] 2023-07-19 13:39
can you try setting the following environment variable? (in case it's the background sandboxes)

    DUNE_CONFIG__BACKGROUND_SANDBOXES=disabled

**Comment by emillon** [comment] 2023-07-19 14:15
Ok, thanks! I'll try to reproduce that locally.

**Comment by hhugo** [comment] 2023-07-20 09:45
issue also exists with dune 3.9.0

**Comment by emillon** [comment] 2023-07-21 10:17
OK, I managed to reproduce this locally. It's an issue with the shared cache. You can disable it on Windows as a workaround.

**Comment by emillon** [comment] 2023-07-21 13:49
I'm struggling to bisect this precisely, but I think there's a race condition in `Fpath.rm_rf` (used here): 

https://github.com/ocaml/dune/blob/92d88482edb5c97a28609257ea0cec5271a5a017/otherlibs/stdune/src/fpath.ml#L135-L138

If something has created a file in the directory between `clear_dir` (which reads the directory) and `rmdir`, there is going to be an error in `rmdir`. But that would be an issue for all OSes though.

**Comment by nojb** [comment] 2023-07-21 13:58
If you can reproduce easily, perhaps it is a good idea to list the contents
of the directory in question before calling `rmdir`; it may help figuring
out the root cause of the issue.

Le ven. 21 juil. 2023 à 15:49, Etienne Millon ***@***.***> a
écrit :

> If something has created a file in the directory between clear_dir (which
> reads the directory) and rmdir, there is going to be an error in rmdir.
> But that would be an issue for all OSes though.
>

**Comment by emillon** [comment] 2023-07-21 14:09
Good idea. These are ocaml source files. For example when running `make dev`, they are bits of dune source code. They are marked readonly.
Either we're creating files we can't remove on Windows (unlikely since I don't think we changed anything related to that recently), or there's a race going on. I verified that disabling background sandboxes does not change this, so I'm still confused. I'll continue investigating.

**Comment by emillon** [comment] 2023-07-21 14:25
Disabling background sandboxes fixes this. So I have a theory:

- tempdir D is created
- some file F is copied in there
- a background thread is started, asking for the digest of F
  - F is opened in this thread
- tempdir D is removed using `Fpath.rm_rf`
  - `unlink_no_err` is called on F. on Windows, this is an error because the file is open. The file is left behind.
  - `rmdir` fails because the directory is not empty.

Which means that we should either retry deleting, have a sort of lock, or just ignore `rmdir` errors in that position.

**Comment by emillon** [comment] 2023-07-21 15:27
I filed #8243 as a tentative fix; probably not the best we can do.
In summary:
- you're affected if:
  - you're on Windows
  - AND you're using the shared cache
  - AND you're using Dune 3.9.0 or 3.9.1
- you can mitigate this by:
  - disabling the dune cache (`export DUNE_CACHE=disabled`, disable in setup-ocaml, etc)
  - OR set `DUNE_CONFIG__BACKGROUND_DIGESTS=disabled`

**Comment by rgrinberg** [comment] 2023-07-23 14:52
The offending function is the following:

```ocaml
  let store_skipping_metadata ~mode ~targets ~compute_digest :
      Store_artifacts_result.t Fiber.t =
    Dune_cache_storage.with_temp_dir ~suffix:"artifacts" (function
      | Error exn -> Fiber.return (Store_artifacts_result.Error exn)
      | Ok temp_dir -> (
        match store_targets_to ~temp_dir ~targets ~mode with
        | Error exn -> Fiber.return (Store_artifacts_result.Error exn)
        | Ok () -> (
          compute_digests_in ~temp_dir ~targets ~compute_digest >>| function
          | Error exn -> Store_artifacts_result.Error exn
          | Ok artifacts ->
            let result = store_to_cache_from ~temp_dir ~mode artifacts in
            Store_artifacts_result.of_store_result ~artifacts result)))
```

Where we:

1. Create a temporary directory
2. Link or copy the targets into it
3. Compute the digests
4. Clear the temporary directory and remove it (this is the step that fails)

From what I see, we only remove the directory once all the digests have been computed and temporary directories are never reused. So I don't really see the potential for a race. @nojb could you have a look at this function and perhaps see if it's doing something wrong on windows?

**Comment by nojb** [comment] 2023-07-23 22:15
> @nojb could you have a look at this function and perhaps see if it's doing something wrong on windows?

I took a quick look, but could not spot anything obvious. Looking at the code of `Fpath.rm_rf` I see that `Fpath.clear_dir` ignores errors when unliking files in the directory: https://github.com/ocaml/dune/blob/6eecf7edf503e2327fc101ca26f33e1693b8cda6/otherlibs/stdune/src/fpath.ml#L131
@emillon it may be interesting to know if any of the calls to `unlink` fail (which could explain the non-empty directory in a different way than a race condition). Could you test your reproduction replacing `unlink_no_err` by plain `unlink`?

**Comment by emillon** [comment] 2023-07-24 10:48
I assumed that the digest thread would outlive `with_temp_dir` here, indeed. I'll try to see whether that's the case.

**Comment by emillon** [comment] 2023-07-24 12:45
There's something a bit weird going on:

![image](https://github.com/ocaml/dune/assets/496345/7dc92984-4221-47e7-80ae-6c5e401efdb0)

I highlighted the background workers in yellow. In some cases, the file descriptor is not closed (see `Per_item_intf.cmi`, thread 12716), and this is what causes the issue after (in the main thread, this file cannot be deleted).

**Comment by emillon** [comment] 2023-07-24 13:08
I am very puzzled. We see the two reads with `END_OF_FILE` which mean we've entered that loop:

https://github.com/ocaml/dune/blob/74893232e3bbcce8f308ca9fca92abf6419617c1/src/dune_digest/dune_digest_stubs.c#L32

We know that the function has returned some data because the async job has returned.

So I don't get why `Unix.close` doesn't fire here:

https://github.com/ocaml/dune/blob/74893232e3bbcce8f308ca9fca92abf6419617c1/src/dune_digest/dune_digest.ml#L27

**Comment by emillon** [comment] 2023-07-24 13:50
I verified that `Unix.close` doesn't raise at that point, so that's not an error caught too early.
I'll have to dig a bit into that. I think that looks like a fd vs channels issue; I'll try passing `_O_NOINHERIT` at `open` to match the semantics of channels and maybe try a completely different stub on windows.

**Comment by emillon** [comment] 2023-07-24 15:39
I think I'm on to something because #8262 seems to fix this.

**Comment by nojb** [comment] 2023-07-24 15:42
> I think I'm on to something because #8262 seems to fix this.

Good find! Out of curiosity, did you try replacing `Unix.close` by a C stub that does `CloseHandle(Handle_val(v_fd))` instead of `_close(win_CRT_fd_of_filedescr(v_fd))`?

**Comment by nojb** [comment] 2023-07-25 09:41
I am reopening this; #8243 is not really a "solution" for this issue.

**Comment by emillon** [comment] 2023-07-25 09:45
It's a solution in the sense that it prevents dune from crashing. I'll open a new issue to track "let's reenable background digests on windows". (and I'll close this one otherwise it'll keep being closed whenever a branch containing the fix is pushed, sorry about that)

**Closed by emillon** 2023-07-25 09:45 UTC
Labels: bug, windows

**Comment by nojb** [comment] 2023-07-25 09:46
> I'll open a new issue

OK, thanks!
