### ISSUE TITLE
"Invalid package table" when locking topkg

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#9753] opened 2024-01-16 10:17 UTC
Hi, I'm getting a code error when trying to lock topkg.

## Expected Behavior

```
Internal error, please report upstream including the contents of _build/log.
Description:
  ("Invalid package table",
  { missing dependency =
      { missing package = "topkg"; dependency of = "astring" }
  ; missing dependency = { missing package = "topkg"; dependency of = "bos" }
  ; missing dependency = { missing package = "topkg"; dependency of = "fmt" }
  ; missing dependency =
      { missing package = "topkg"; dependency of = "fpath" }
  ; missing dependency =
      { missing package = "topkg"; dependency of = "jsonm" }
  ; missing dependency =
      { missing package = "topkg"; dependency of = "logs" }
  ; missing dependency =
      { missing package = "topkg"; dependency of = "rresult" }
  ; missing dependency =
      { missing package = "topkg"; dependency of = "uutf" }
  ; missing dependency =
      { missing package = "topkg"; dependency of = "webbrowser" }
  })
```

## Reproduction

```
opam source topkg.1.0.7
cd topkg.1.0.7
dune pkg lock --root .
```

## Specifications

- Version of `dune` (output of `dune --version`):
ad45e93aa2f7a3808f8faea847850dba5c29ed84

**Comment by emillon** [comment] 2024-01-16 10:18
cc @gridbugs

**Comment by rgrinberg** [comment] 2024-01-16 16:13
It's an issue with overlapping package deps. The issue is that we have the following dependency chain:

`topkg-care` (local) -> `astring` (repo) -> `topkg` (local)

Our dependencies are only allowed to go from `local` to `repo` at the moment. We would like to fix this problem eventually (as described in this ticket https://github.com/ocaml/dune/issues/8652), but it's a bit involved and I'm not sure I'll have time to do it the near future.

For now, I suggest that we create a test and add a nice error message explaining the issue.

**Comment by gridbugs** [comment] 2024-01-17 05:14
Fixed in https://github.com/ocaml/dune/pull/9760

**Comment by emillon** [comment] 2024-01-17 08:56
Thanks!

**Closed** 2024-01-17 09:03 UTC
Labels: bug, package management
