### ISSUE TITLE
Dune clean fails on USB stick

### ISSUE THREAD

**Issue by yannl35133** [ocaml/dune#2964] opened 2019-12-11 15:55 UTC
When I try to run `dune clean` on my project which is located on a USB stick, the call to `rmdir` is refused as `Directory not empty`.
It works perfectly fine if I copy it on the computer.

How to reproduce:
In an empty folder, on the command line
`dune build`
`dune clean`
`Error: rmdir: _build: Directory not empty`

I'm on Kubuntu 19.10,
dune 2.0.0 from opam (BTW, is it normal that `dune --version` echoes `n/a` ?)

**Comment by diml** [comment] 2019-12-11 16:07
Wait, building on a usb stick???

More seriously, I can't think of what in Dune would cause this behaviour. `dune clean` is barely more than a glorified `rm -rf _build`. When the call to `rmdir` fails, is the directory really empty?

**Comment by diml** [comment] 2019-12-11 16:09
> BTW, is it normal that dune --verision echoes n/a ?

No, that's fixed in master.

**Comment by nojb** [comment] 2019-12-11 16:10
I've seen issues with `dune clean` on Windows complaining that `_build/log` could not be unlinked. May be related. Don't know how to reproduce it yet. I think @ejgallego also saw this problem.

**Comment by diml** [comment] 2019-12-11 16:24
What are the file systems in each cases? It could also be an issue with dune holding on to an open file inside `_build` such as `_build/log`, though I believe we don't open the log file for `dune clean`.

**Comment by nojb** [comment] 2019-12-11 16:26
In my case, it is `ntfs`.

**Comment by yannl35133** [comment] 2019-12-11 17:29
NTFS also (for the key).
As for dune holding on to an open file, why would it do it on a stick but not on my computer ?
Regarding the USB stick, I'm still a student and I have not learned how to use git, I code my (relatively small) project both on my computer and at school, and I cannot control much there.

**Comment by nojb** [comment] 2019-12-11 17:37
> What are the file systems in each cases? It could also be an issue with dune holding on to an open file inside `_build` such as `_build/log`, though I believe we don't open the log file for `dune clean`.

I just did a quick experiment and the log is indeed opened when doing `dune clean` (sorry, don't have time to investigate further at the moment):
```
$ _build/install/default/bin/dune.exe clean
init
Raised by primitive operation at file "src/stdune\\log.ml", line 23, characters 42-69
Called from file "bin\\common.ml", line 73, characters 2-13
Called from file "bin\\common.ml" (inlined), line 97, characters 2-29
Called from file "bin\\main.ml", line 92, characters 4-40
Called from file "vendor/cmdliner/src\\cmdliner_term.ml", line 25, characters 19-24
Called from file "vendor/cmdliner/src\\cmdliner.ml", line 146, characters 9-16
Called from file "vendor/cmdliner/src\\cmdliner.ml", line 176, characters 18-36
Called from file "vendor/cmdliner/src\\cmdliner.ml", line 312, characters 20-46
Called from file "bin\\main.ml", line 193, characters 10-51
Error: unlink: _build\install\default\bin\dune.exe: Permission denied
```

**Comment by ejgallego** [comment] 2019-12-11 17:44
Seems a duplicate of #2921

**Comment by yannl35133** [comment] 2019-12-11 17:50
I just checked, the problem only happens on my NTFS key. Should I change title to NTFS filesystem?

**Comment by diml** [comment] 2019-12-12 08:24
@yannl35133 yeah, that seems to be NTFS related.

Regarding the file being kept open, deleting an open file is fine most of the time, but maybe it's not on NTFS.

**Comment by nojb** [comment] 2019-12-12 08:32
In order to be able to delete an open file under Windows, you need to open it using the `FILE_SHARE_DELETE` flag (`O_SHARE_DELETE` flag in `Unix`).

**Comment by diml** [comment] 2019-12-12 08:41
Yeah, we use that flag in a few cases. Maybe we should use it more systematically. In any case, it doesn't seem useful to open the log file in `dune clean` so we might as well not do it.

**Closed** 2019-12-12 13:48 UTC

**Comment by yannl35133** [comment] 2019-12-12 17:49
Thanks for this. When can we expect this to be included in opam's version?

**Comment by diml** [comment] 2019-12-16 10:58
We started the release of Dune 2.1.0, so it should be in opam soon.
