### ISSUE TITLE
C library linking...

### ISSUE THREAD

**Issue by progman1** [ocaml/dune#2770] opened 2019-10-18 16:21 UTC
I tried to create a library that specified an object file to link against without it being through a supplied stubs file, and it does not work with this alone:
 (c_library_flags (-lmylib))

but I can have it work for byte/native with
 (flags (-custom)) /  (flags (-linkall))

respectively.
but is there a way to get dune to do this automatically? (as per exec ./main.exe & ./main.bc)

thanks.

**Comment by progman1** [comment] 2019-10-25 13:47
all I have is a .so stub file, built outside of ocaml, that I want to link with this code:
external stubtest: unit->unit
let _= stubtest()

I would like to run 'dune exec ./main.exe' or 'dune exec ./main.bc' 
and have it link it in whatever way it wants.
but the only way I have found to get that behaviour is too edit the dune file
and swap the (flags ...) line as above.

I thought I would try a C stub example handled by dune in its entirety and examine the commands
dune uses to do the job:
stubs.c:
#include <stdio.h>
#include "caml/mlvalues.h"

value caml_test_stub(value i){
  printf("test stub: %d\n", Int_val(i));
  return Val_unit;
}

cstubs.ml:
external test: int ->unit ="caml_test_stub"

main.ml:
let _=
  Cstubs.test 999

dune:
(executable
 (name main)
 (modules main)
 (libraries cstubs)
)

(library
 (name cstubs)
 (modules cstubs)
 (c_names stubs)
)

it works for native: 'dune exec ./main.exe'
but surprisingly to me does not for bytecode 'dune exec ./main.bc':
Error: Error on dynamically loaded library: dllcstubs_stubs.so: dllcstubs_stubs.so: cannot open shared object file: No such file or directory

the _build directory shows no .so library having been built but there is a static lib:
_build/default/cstub/libcstubs_stubs.a

there's something wrong there - using dune v1.9.3

the working native build is also built with a static library.
in regard to the original question, in native, the -linkall  has the desirable result of linking the .so library dynamically.
to the executable.

and indeed

**Comment by nojb** [comment] 2019-10-26 07:58
A couple of remarks:

- I don't think the `-linkall` flag is relevant in your case
- The native binary is always linked statically with the C stubs
- The `.bc` binary is "pure bytecode" which means that the C stubs are not linked statically, but dynamically. This means you need to pass the path to the `.so` file in the `CAML_LD_LIBRARY_PATH` variable when running it (`dune exec` does not do this for you).
 - Finally note that the `.so` is not necessary to **build** the bytecode executable, just to run in. This is why the `.so` may not be present in the `_build` directory. But it should appear if you do `dune build @all`.

See #108 for more.

**Comment by nojb** [comment] 2019-10-26 07:59
I am closing this as duplicate of #108, but feel free to reopen if you have more questions. Thanks!

**Closed by nojb** 2019-10-26 07:59 UTC

**Comment by houndofsound** [comment] 2019-10-29 09:21
you're right - the -linkall was not relevant.
the difference between supplying a .so library alone and supplying the C files, is that dune 
handles the latter case by arranging -dlllib at the OCaml library creation stage (as well as making the .so) . It also produces a static version of the object code and uses -cclib, which means the OCaml library is good for either dll or static while dune links it for dll functionality when producing an executable. 
the referenced thread did indeed solve my problem - dune has (ocamlc_flags ...) and (ocamlopt_flags ...) for making byte/optimised distinctions.  so (ocamlc_flags -custom) does the job.
the binary comes out 600k larger on my system and takes 1s longer to produce - probably worse if I hadn't switched to SSD. 
it's worth noting that the OCaml runtime could be turned into a .so and a stub entry point created that incorporated it and any user-requested .so libraries. this would have the benefit
of ensuring the binary did not link without resolved dll paths, visible by /bin/ldd inspection, and
the elimination of the need to set CAML_LD_LIBRARY_PATH .

and
