### ISSUE TITLE
Allow the use of `c_names` in executable stanzas

### ISSUE THREAD

**Issue by samoht** [ocaml/dune#2561] opened 2019-08-19 15:57 UTC
Is there a reason `c_names` are not accepted in executable stanza? If not, that would be great to allow it :-)

**Comment by emillon** [comment] 2019-08-19 16:04
Duplicate of #1858

**Comment by emillon** [comment] 2019-08-19 16:04
(agree that it'd be great!)

**Comment by samoht** [comment] 2019-08-19 16:43
ha yes, thanks for noticing :-)

**Closed** 2019-08-19 16:43 UTC
