### ISSUE TITLE
Error: File unavailable: <opam-root>/lib/base/sexplib.cmxs during dynload

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [ocaml/dune#4258] opened 2021-02-18 23:43 UTC
## Actual Behavior
When I dynload the package `sexplib` as part of compilation using Dune with a dependency on `base`, I get the following error:
```
Error: File unavailable:
<opam-root>/lib/base/sexplib.cmxs
```
The dynload happens as part of Coq, but I don't think that is relevant. The same happens when dynloading  `fmt` while depending on `re`. This issue appears to be related to #1841.

## Reproduction
Dune file
```
(coq.theory
 (name Test)
 (package coq-test)
 (libraries base)
)
```
Coq file:
```
Add ML Path "<opam-root>/lib/sexplib0".
Add ML Path "<opam-root>/lib/sexplib".
Add ML Path "<opam-root>/lib/parsexp".

Declare ML Module "sexplib0".
Declare ML Module "parsexp".
Declare ML Module "sexplib".
```

## Specifications

- Version of `dune` (output of `dune --version`): 2.8.2
- Version of `ocaml` (output of `ocamlc --version`): 4.11.1
- Operating system (distribution and version): Arch linux

- Link to gist with verbose output (run `dune` with the `--verbose` flag): https://gist.github.com/LasseBlaauwbroek/ae8abd209eeb46cb33afcc5126694f22

**Comment by jeremiedimino** [comment] 2021-03-01 09:24
`<opam-root>/lib/base/sexplib.cmxs` is definitely the wrong file, it should be `<opam-root>/lib/sexplib/sexplib.cmxs`.

**Comment by ejgallego** [comment] 2021-03-01 15:43
I cannot reproduce with the example you provided, things just work fine.

**Comment by LasseBlaauwbroek** [comment] 2021-03-04 23:39
I did some further experiments, and it seems I can only reproduce this with coq8.11(.2), not with 8.12 and 8.13. This is completely baffling me...

**Comment by ejgallego** [comment] 2021-09-22 09:08
I think this was due to some packaging issues of base / sexplib themselves, recent versions don't seem to have this problem, so indeed, newer opam switches may not suffer from this problem.

Closing for now, but feel free to reopen if something dune specific pops up.

**Closed by ejgallego** 2021-09-22 09:08 UTC
