### ISSUE TITLE
Hello World example on dune.build no longer works

### ISSUE THREAD

**Issue by jamiahx** [ocaml/dune#5751] opened 2022-05-22 14:31 UTC
## Expected Behavior
compile hello_world.exe

## Actual Behavior
build fails with "Error: I cannot find the root of the current workspace/project."

## Reproduction

1. follow instructions on dune.build

## Specifications

- Version of `dune` (output of `dune --version`): 3.2.0
- Version of `ocaml` (output of `ocamlc --version`): 4.12.0
- Operating system (distribution and version): ChromeOS 101.0.4951.59

## Additional information 
likely the example is obsolete due to behavior outlined in
https://github.com/ocaml/dune/blob/077d1b3de2b538b1e6a71fdda24f302b3f0d58da/CHANGES.md?plain=1#L296-L297

- Link to gist with verbose output (run `dune` with the `--verbose` flag):
https://gist.github.com/jamiahx/68eb1a5a9c0e1898a5979d670bb6dce0

**Comment by emillon** [comment] 2023-04-07 13:04
Duplicate of #7457

**Closed by emillon** 2023-04-07 13:04 UTC
Labels: docs
