### ISSUE TITLE
unlocated "I can't determine what library/executable the files produced by this stanza are part of."

### ISSUE THREAD

**Issue by trefis** [ocaml/dune#1876] opened 2019-02-26 10:21 UTC
For example:
```
$ dune build
Error: I can't determine what library/executable the files produced by this stanza are part of.
```

In my case, the stanza in question is a menhir stanza, which is located in one of my 23 dune files.
It would be nice to give a location to that error.

**Comment by rgrinberg** [comment] 2019-02-26 11:04
That's quite strange, because the error message in question has a loc attached:

```
            (Build.fail ~targets
               { fail = fun () ->
                   Errors.fail m.loc
                     "I can't determine what library/executable the files \
                      produced by this stanza are part of."
               })
```

Do you have a branch that so I can try to reproduce this.

**Comment by diml** [comment] 2019-02-26 12:39
I just checked in `dune_file.ml` and we do `loc = Loc.none` for menhir stanza... Don't know how that happened

**Comment by trefis** [comment] 2019-02-26 13:12
I guess you don't need the repro anymore then, but in any case: just pull the branch `unlocated-dune-error` of merlin and run:
```
$ dune build src/ocaml/preprocess/407/parser_raw.ml
```

**Closed** 2019-02-26 14:41 UTC
