### ISSUE TITLE
Mli only hack is broken in some cases.

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#469] opened 2018-01-31 18:50 UTC
Try `$ jbuilder build -p vchan` in the https://github.com/mirage/ocaml-vchan repo.

```
Warning: Module S in _build/default/lib doesn't have a corresponding .ml file.
Modules without an implementation are not recommended, see this discussion:

  https://github.com/ocaml/dune/issues/9

In the meantime I'm implicitely adding this rule:

(rule (with-stdout-to s.ml
       (progn
        (echo "[@@@warning \"-a\"]\nmodule rec HACK : sig\n")
        (cat s.mli)
        (echo "\nend = HACK\ninclude HACK\n"))))

Add it to your jbuild file to remove this warning.
No rule found for lib/s.ml
```

**Comment by diml** [comment] 2018-02-01 00:09
I thought again about .mli only modules, and a way to mitigate the problems would be to allow them but require them to be listed in the library/executable stanza. This would catch cases where the user renames the .ml but forget to rename the .mli and would allow expert users to have .mli only modules. We could have that in jbuild files:

```scheme
(library
 (...
  (modules_with_implementation (s))))
```

**Comment by rgrinberg** [comment] 2018-02-01 08:35
Will mli only modules be usable with with `(wrapped true)`? I recall that was a problem with adding support.

Also, is this back serious enough to pull the release? I'm leaning towards know because there are simple workarounds (like not using mli only modules or just adding the rule dune tells you to). But we should still investigate the cause here of course.

**Comment by dra27** [comment] 2018-02-01 08:46
As I noted in Slack, the problem is in the message referring to `in _build/default/lib` where before it would just have referred to `lib`. The problem goes away if the context dir is no longer prepended, but my guess was that that is not the correct solution.

We could just limit vchan to beta16 for now - although that does consequently constrain a few other libraries. Is the full fix for this really non-trivial?

**Comment by diml** [comment] 2018-02-01 09:37
Ah you're right, i initially looked at the wrong line. The build dir is already prepended now... The fix should be simple then

**Comment by diml** [comment] 2018-02-01 09:39
@rgrinberg, we can do the same as omp: https://github.com/ocaml-ppx/ocaml-migrate-parsetree/blob/252a8129010f82c5e15a2b42c363f1fc66ef3389/src/migrate_parsetree.ml#L87

**Comment by diml** [comment] 2018-02-01 10:12
I'm looking at a fix

**Closed** 2018-02-01 10:50 UTC
