### ISSUE TITLE
Support opam/ folder to declutter root folder from *.opam files

### ISSUE THREAD

**Issue by mjambon** [ocaml/dune#7329] opened 2023-03-15 21:16 UTC
Problem: We have too many *.opam files at the root of our project. Opam supports putting those files into an `opam/` folder but it seems dune doesn't support it.

I originally asked the question on Discuss at https://discuss.ocaml.org/t/how-to-avoid-having-a-bunch-of-empty-opam-files-at-the-project-root/11675.

Desired behavior: we care about decluttering our root folder so as to make the rendered README more visible on our [GitHub project page](https://github.com/returntocorp/semgrep). The solution might be to look up *.opam files in the root `opam/` folder as opam does. I suspect there may be good reasons why it's not the case already, I don't know.

## Example

Move all these files out of the way:
![image](https://user-images.githubusercontent.com/343265/225445185-58f8c980-a04a-4ef3-a1d9-c1a998150a42.png)

**Comment by hhugo** [comment] 2023-03-15 22:53
Duplicate of https://github.com/ocaml/dune/issues/5571

**Closed** 2023-03-16 02:28 UTC
Labels: feature-request

**Comment by emillon** [comment] 2023-03-16 09:50
And as for the particular issue you're having, as answered on discuss you can define the packages in `dune-project` rather than using opam files.
