### ISSUE TITLE
clear-on-rebuild not cleaning terminal and duplicating errors

### ISSUE THREAD

**Issue by ulugbekna** [ocaml/dune#5568] opened 2022-04-10 17:39 UTC
## Expected Behavior

`dune build @all -w --terminal-persistence=clear-on-rebuild` clears the terminal on every re-build. 

## Actual Behavior

1) it doesn't clear the terminal
2) after `k`-th rebuild, the same diagnostic is reported twice 🤔

Video: 

https://user-images.githubusercontent.com/16353531/162632026-c533c1dd-b41e-4e15-a53a-be5fe04c8e51.mov

## Reproduction

Run `dune build @all -w --terminal-persistence=clear-on-rebuild` in a project with syntax/type errors. 

The video above is a simple `dune init executable test` project. 

## Specifications

- Version of `dune` (output of `dune --version`): 3.0.3
- Version of `ocaml` (output of `ocamlc --version`): 4.14.0
- Operating system (distribution and version): macOS Monterey 12.2.1 (21D62)

## Additional information

I have this problem both in vscode embedded terminal and macos iterm with zsh.

**Comment by rgrinberg** [comment] 2022-04-27 18:50
I think this is a duplicate of #5482

**Closed by rgrinberg** 2022-04-27 18:50 UTC
