### ISSUE TITLE
opam build fails on macos due to incorrect zstd version

### ISSUE THREAD

**Issue by mvanier** [ocaml/dune#10392] opened 2024-04-05 07:31 UTC
## Expected Behavior

When doing an `opam upgrade` on MacOS Ventura 13.6.6 (Apple Silicon), dune should build successfully.

## Actual Behavior

`opam upgrade` fails with this message:

```
#=== ERROR while compiling dune.3.14.2 ========================================#
# context     2.1.5 | macos/arm64 | ocaml-base-compiler.5.1.1 | https://opam.ocaml.org#3ae17654
# path        ~/.opam/5.1.1/.opam-switch/build/dune.3.14.2
# command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml boot/bootstrap.ml -j 11
# exit-code   2
# env-file    ~/.opam/log/dune-51906-aa376d.env
# output-file ~/.opam/log/dune-51906-aa376d.out
### output ###
# ocamlc -output-complete-exe -w -24 -g -o .duneboot.exe -I boot -I +unix unix.cma boot/libs.ml boot/duneboot.ml
# ld: warning: directory not found for option '-L/opt/homebrew/Cellar/zstd/1.5.5/lib'
# ld: library not found for -lzstd
# clang: error: linker command failed with exit code 1 (use -v to see invocation)
# File "boot/duneboot.ml", line 1:
# Error: Error while building custom runtime system
```

## Reproduction

Type `opam update` and `opam upgrade` on a MacOS system.

## Specifications

- Version of `dune` (output of `dune --version`): 3.14.0
- Version of `ocaml` (output of `ocamlc --version`): 5.1.1
- Operating system (distribution and version): MacOS Ventura 13.6.6 (Apple Silicon)

## Additional information 

The error seems to be caused because Homebrew now installs `zstd` version 1.5.6 (which I have installed),
but the opam build information for dune requires 1.5.5.

**Comment by emillon** [comment] 2024-04-05 07:52
duplicate of #10368

**Comment by emillon** [comment] 2024-04-05 07:53
Hi! This is an issue with your ocaml installation. You can try the workaround in the listed issue. Thanks

**Closed by emillon** 2024-04-05 07:53 UTC
