### ISSUE TITLE
Please avoid retagging the same version twice

### ISSUE THREAD

**Issue by ArchangeGabriel** [ocaml/dune#2250] opened 2019-06-05 09:38 UTC
Yesterday, 1.10.0 was released… again. Indeed, it was already released last week. Doing so is quite a bad practice, for a very large number of reasons (starting by distros not being able to detect a new version, or user reporting bugs with 1.10.0 that are fixed in… 1.10.0, second release).

So, if there was a bug in 1.10.0, fine, just release 1.10.1. ;) Everyone makes mistakes. :)

**Comment by rgrinberg** [comment] 2019-06-05 09:41
Indeed, that's what I'd prefer as well. Unfortunately, there's some pretty strong quality control at opam-repository that isn't easy to reproduce locally.

One alternative to the current situation is to simply close the PR on opam-repository and release a new version. I'm not against that, but it would mean that some versions of dune would be absent from opam-repository. However, that seems fine for a package repo with heavy gate keeping like opam-repository.

**Comment by ArchangeGabriel** [comment] 2019-06-05 09:45
FTR, I don’t know anything about how opam works, I’m just packaging dune for ArchLinux because it is required by other packages. And we already have the 1.10.0 version since May 30th. So technically speaking I can re-release as 1.10.0-2, but this kind of thing should be avoided.

While there would be a missing version on opam, there will be two 1.10.0 version elsewhere in the other case…

**Comment by rgrinberg** [comment] 2019-06-05 09:53
@avsm @diml are you ok with some releases being absent from opam-repository? I agree with the OP that the situation would be better addressed by releasing 1.10.1 and just not having 1.10 make it to opam

**Comment by diml** [comment] 2019-06-05 11:07
Fine by me!

**Comment by avsm** [comment] 2019-06-05 14:32
Hang on, this isn't quite ok with me.  Dune shouldn't lose the ability to define its own release procedure just because some distros take "git tag" as a sign of release.  But that isn't our process.

Our current release process is:

- local dune tests are good and some manual testing occurs
- git tag ocaml/dune, generate archive
- submit to opam where extensive tests occur
- iterate the git tag until no showstoppers found in opam
- merge to opam-repo, at which point the dune git tag is immutable

This isn't the ideal release process of course, but that's what it is right now.  @ArchangeGabriel is there somewhere in Arch to note this so that a git tag doesn't result in a release being cut before it's official from dune?

We could improve on this by making the opam releases as actual release candidates, e.g. `1.10+rc1` and submitting those as draft PRs with opam to do the revdeps testing.  Is that something you'd consider for the 1.10.1 release, rgrinberg?

@ArchangeGabriel can the arch release of 1.10.0-0 just be marked as broken so that the update will be used?  I'm not familiar with Arch's release mechanisms, so your guidance would be appreciated on how to avoid having two live dune.1.10.0 packages.

**Comment by ArchangeGabriel** [comment] 2019-06-05 15:42
Well if it really was just a git tag, I wouldn’t even have noticed it. But you use GitHub releases, so at this point I definitively consider this as a release. For instance Node might have some days between tagging and releasing, exactly because they first follow all the rest of their release process (generating tarballs, QA, etc.) and only then transform the tag into a GitHub release. ;)

So regarding the release process, I’m fine with either rc or delay between tag and release, though the former is probably cleaner if you need to retag (after all, that’s what rc means).

Regarding the current situation for Arch, as stated above I can replace 1.10.0-1 by a newer 1.10.0-2 that is rebuilt from the new sources. In the (unlikely) case someone reports an issue while using the Arch package, they should be asked for the exact version of the package to clear any ambiguity, but other than that it should be fine (1.10.0-1 other than 1.10.0-1 is not reproducible anymore, but that won’t be the first nor the last package in that regard).

**Comment by avsm** [comment] 2019-06-05 16:03
Thanks for clarifying @ArchangeGabriel -- and I'm definitely not criticising your upload of the release.  It's just that we should be sure that our project-local release processes are unambiguous for distros to see. You've been very helpful in opening this issue for us to do so.

**Comment by rgrinberg** [comment] 2019-06-05 22:31
I'm OK with making RC's. I feel like that's quite similar to what we've tried with betas however. The issue wast that we didn't want users to churn through upgrading through our betas. Although personally, I don't see such a huge with this. It would only create issues for users who blindly `$ opam upgrade`

**Comment by diml** [comment] 2019-06-06 06:50
One thing I don't like too much with betas or rcs is that after a while the opam repository will be full of beta and rc versions of Dune. I'm fine with it if they are eventually deleted from both the opam reposiotry and the github release page, to keep things clean.

**Comment by rgrinberg** [comment] 2019-06-06 09:01
Not totally related, but it seems wrong to me to consider the limitations of opam-repository (or any other particular software repository) when designing our release process. For example, if it's a problem for opam-repository to handle multiple too many versions of a particular package, then it's something that they should solve. I do not think that we should be adding the maintenance of opam-repository to our concerns.

So if the only objection to RC's is this one, I don't find it very convincing.

**Comment by diml** [comment] 2019-06-06 10:27
> Not totally related, but it seems wrong to me to consider the limitations of opam-repository (or any other particular software repository) when designing our release process.

I agree with you on this point. At the same time, it seems to me that opam is still the tool used by the majority of the OCaml community and it is also a really good testsuite for Dune that help us find a lot of regressions in new releases. Opam maintainers have also been very helpful in triaging and idenfiying regressions at release time. In summary, a lot of good things have come out of the close Dune<->opam collaboration, so it seems natural to me that we treat opam as a privileged software repository.

IIUC, the main problem is not really about the tagging but more the fact that we use the github release page immediately. What about we add a second step in the dune-release process? I believe we can mark a release as a "draft" on github, so `dune-release` could do that at first, and when the release has been merged in the opam repository, we would run another `dune-release` command that would remove the "draft" status. What do you think? @NathanReb, is that doable?

**Comment by NathanReb** [comment] 2019-06-06 10:42
That sounds like a good plan. I wonder if we could use some kind of hook so that merging the opam-repo PR triggers  the "undrafting" of the release. That would make opam package maintainers life easier as it's likely that the amount of time between the opening and the merging of opam-repo PRs is going to be much longer than any of the other release process steps.

**Comment by diml** [comment] 2019-06-06 10:54
Indeed, that would be really nice!

**Comment by rgrinberg** [comment] 2019-06-06 10:57
Okay, but do we need an interim solution? There seem to be other priorities in dune-release at the moment. I'm still not quite satisfied with this solution because the current release process is already so complex and not particularly reliable. Adding at least two more interactions with external services is bound to take a while to do correctly.

Is there just a way for me to do the rev deps test before doing a release? If this is part of our release process (de-facto it is), it would make sense for me to just run it rather than optimistically making a release.

**Comment by diml** [comment] 2019-06-06 11:08
Alright, let's plan a videoconf meeting to discuss this further with you, Anil, Nathan and me. We'll synchronise on slack to find a time.

For the immediate future, let's continue as we have been doing so far.

**Comment by ArchangeGabriel** [comment] 2019-06-06 12:22
So should I move on with releasing the new 1.10.0 into ArchLinux? For the next releases, I can wait for the package to appear in opam for instance, until you further figure out a new process. ;)

**Comment by diml** [comment] 2019-06-06 12:25
yep, 1.10.0 was merged in the opam-repository this morning, so it's safe to proceed

**Comment by hongchangwu** [comment] 2019-06-06 17:59
@ArchangeGabriel btw when packaging OCaml stuff I've found opam-repository to be a much more reliable source than GitHub.

**Comment by tchajed** [comment] 2019-06-06 21:58
This force push also confused Doom Emacs' upgrade code: https://github.com/hlissner/doom-emacs/issues/1473.

**Comment by UnixJunkie** [comment] 2019-08-27 05:56
> Indeed, that's what I'd prefer as well. Unfortunately, there's some pretty strong quality control at opam-repository that isn't easy to reproduce locally. This requires me to redo releases to get through it.

Just create tags which are not proper release numbers, until the tagged software is fine regarding
quality control.
For example, you want to tag and release v1.2.0.
First tag as v1.2.0-test00.
If needed, correct then tag the software one more time as v1.2.0-test01
etc.
Once QC are passing, retag one more time the software with a better tag name.

**Comment by rgrinberg** [comment] 2021-10-18 03:25
Sorry for all the troubles. We stopped retagging a while ago.

**Closed by rgrinberg** 2021-10-18 03:25 UTC
