### ISSUE TITLE
"dune describe workspace" should work without executables as well

### ISSUE THREAD

**Issue by smuenzel** [ocaml/dune#5747] opened 2022-05-20 05:14 UTC
dune describe workspace currently only works when there are executables in the workspace, and outputs "()" otherwise.
It should output something when a project only consists of libraries as well (or at least an error instead of "()").
Specifically, module dependencies are also very useful for libraries.

**Comment by rgrinberg** [comment] 2022-05-21 14:23
ping @esope

**Comment by sim642** [comment] 2022-05-22 15:41
The issue is more general than just workspaces with no executables. Absolutely nothing is described about libraries right now. So it's also an issue when most of the logic is in a library and an executable is just a thin wrapper around the library.

**Comment by esope** [comment] 2022-05-22 22:40
@smuenzel and @sim642 : Can you please provide an example, so that I can reproduce the bugs you observe?

**Comment by smuenzel** [comment] 2022-05-23 01:27
I'm very confused now -- I had dune in a state where an "executable" stanza produced output, and "library" produced only "()", but now I can't get it back into this state (and output is produced when i use "library"). I did not upgrade dune (I used 3.1.1) in between.
@sim642 : what is your setup?

**Comment by esope** [comment] 2022-05-23 06:21
``dune describe workspace`` usually produces ``()`` when `dune build` fails, i.e. when your project does not build. ``dune describe workspace`` is not expected to produce anything useful in this case.

**Comment by sim642** [comment] 2022-05-23 07:10
I haven't tried minimizing, but what I tried it on is this https://github.com/goblint/analyzer and dune 3.2, after successful `dune build`. It's a big project with bunch of dune hackery and trickery, so maybe I've just seen some unusual interaction bug.

**Comment by esope** [comment] 2022-05-25 06:18
I can reproduce the issue with ``goblint``. Thanks.
The issue seems to be related to virtual modules, and/or to ``select`` stanzas.

**Comment by esope** [comment] 2022-07-14 15:32
The issue was indeed about the use of virtual libraries. I pushed a fix in PR#5971.

**Comment by esope** [comment] 2022-07-14 16:26
For the record, here is what was happening: if your project was using a virtual library and at least two implementations for that virtual library, then `dune describe` would not produce any information for the libraries of your project (it would only show information about the executables, if there were any).
The issue was in the computation of the transitive closure of libraires, that raised an error by default in the presence of overlapping implementations of virtual libraries. In such a case, the error was treated by discarding all information about the libraries.

**Closed** 2022-07-20 09:42 UTC
