### ISSUE TITLE
Bad interaction between '(mode promote-until-clean)' and tests ran with '-p <pkg>'

### ISSUE THREAD

**Issue by Gbury** [ocaml/dune#4401] opened 2021-03-25 22:50 UTC
## Expected Behavior

When using a file (let's say `test`) that is "promoted until clean" as a dep for a test defined for a specific package `foo`, `dune build @runtest -p foo` should succeed.

## Actual Behavior

`dune build @runtest -p foo` fails with `Error: No rule found for test`.
The conjunction of `(mode promote-until-clean)` and `-p <pkg>` seems to make dune "forget" about how to build some targets. I don't know if that is expected and if so, what is the correct way to do things.

## Reproduction

See https://gist.github.com/Gbury/598f0b6f751767e8a66fe9c508704976

dune file:
```
(rule
  (target test)
  (mode promote-until-clean) ; without this, everything runs fine 
                             ; but with it, dune complains about "No rule found for test"
  (action (with-stdout-to %{target} (run echo foobar)))
)

(rule
  (alias runtest)
  (package foo)
  (deps (:test test))
  (action (diff %{test} reference))
)
```

0. `dune build @runtest` succeeds as can be expected
1. `dune build @runtest -p foo` fails with "Error: No rule found for test"  (make sure to `dune clean` between attempts, particularly after a successful run)
2. If the `(mode promote-until-clean)` is commented out, `dune build @runtest -p foo` succeeds

## Specifications

- Version of `dune` (output of `dune --version`): 2.8.4
- Version of `ocaml` (output of `ocamlc --version`): 4.11.1
- Operating system (distribution and version): archlinux 5.11.9-arch1-1

## Additional information 

- Link to gist with verbose output (run `dune` with the `--verbose` flag):
Output of `dune build @runtest -p foo --verbose` :
https://gist.github.com/Gbury/80ed0220ccdd729781b35d445731de90

In practice, this happens to me in the dolmen project (see e.g. [this dune file](https://github.com/Gbury/dolmen/blob/687ae8b46b0e7df3f414054b31e52a78e9185b31/src/languages/ae/dune#L34-L66 )), where a rule is defined to generate an updated version of menhir's error message file (which is promoted-until-clean, since it is meant to be used as a reference when updating the error messages after changing the grammar), and another rule is defined to use that file to check that all error states have an error message written.

**Comment by jeremiedimino** [comment] 2021-03-26 09:15
I see the problem. `-p` implies `--release`, which implies `--ignore-promoted-rules`. This was intended for rules with `(mode promote)`, which is intended for files that are both generated and committed. Dune ignore such rules during release builds so that it takes the file in the source tree directly rather than re-generating it. This speeds up release builds and can also be used to cut down dependencies.

However, it seems that currently `--ignore-promoted-rules` also ignores rules with `(mode promote-until-clean)`, which is clearly wrong, given that such temporarily promoted files are clearly not meant to be committed in the repository.

I'm marking this as a bug and scheduling it for Dune 3.0. Do you want to give a shot a writing a fix for it? Happy to give you some pointers if yes.

**Closed** 2022-08-01 11:22 UTC
Labels: bug
