### ISSUE TITLE
format-dune-file doesn't preserve multiline text

### ISSUE THREAD

**Issue by Kakadu** [ocaml/dune#5428] opened 2022-02-12 08:50 UTC
## Expected Behavior
The call `dune format-dune-file` lefts multiline text as it is 

## Actual Behavior
All multiline text is shrinked to single line

## Reproduction
dune-project
````
(lang dune 2.9)

(name A)

(package 
  (name A)
  (description 
"\| this is a block
"\| of text"
))

````
after ` dune format-dune-file dune-project`
````
(lang dune 2.9)

(name A)

(package
 (name A)
 (description "this is a block\nof text\"\n"))
````

Also you can observe that last empty line was removed.

## Specifications

- Version of `dune` (output of `dune --version`): 2.9.3
- Version of `ocaml` (output of `ocamlc --version`) 3.13

**Comment by nojb** [comment] 2022-03-04 13:55
Yes, this is known (but thanks for opening an issue about it!).

If I remember the cause is that the internal representation of strings do not keep track of how they were written in the Dune file, so it cannot format them accordingly.

A priori to fix it all you need to do is add a flag at parsing time indicating whether the string was multiline or not and then use the flag at formatting time to do the right thing, but I haven't looked at the details.

**Comment by nojb** [comment] 2022-11-06 09:16
Duplicate of #4021

**Closed by nojb** 2022-11-06 09:16 UTC
Labels: bug
