### ISSUE TITLE
(flags ...)   alternative for individual files?

### ISSUE THREAD

**Issue by houndofsound** [ocaml/dune#2796] opened 2019-10-24 17:18 UTC
there is the (flags (:include ...)) syntax for adding compiler arguments but the docs (latest)
say it is only for library, executable(s), and env stanzas.

I was expecting rule stanza too.
I'm looking for a way to change the compile flags for specific files.
generally flag changes would be great but my use in particular here is to designate a preprocessor where the prepro itself is not necessarily made a dependency.

is there a way to do this now?

**Comment by ejgallego** [comment] 2019-10-24 17:45
Seems a duplicate of #61 , see also #2019

**Closed** 2019-10-30 06:16 UTC
