### ISSUE TITLE
Missing left side panel stanza links

### ISSUE THREAD

**Issue by toots** [ocaml/dune#7143] opened 2023-02-21 14:37 UTC
Looks like the different stanza have disappeared from the left side navigation panel https://dune.readthedocs.io/en/stable/dune-files.html#dune

**Comment by jchavarri** [comment] 2023-02-21 14:45
This is same issue as #7107, caused by jQuery missing, because in latest it does not occur:

https://dune.readthedocs.io/en/latest/dune-files.html#dune

**Comment by emillon** [comment] 2023-02-21 15:45
Yes, that's the same one. I'm looking for a way to fix the `stable` version.

**Comment by emillon** [comment] 2023-02-21 16:04
This is now fixed in `stable` too.

**Comment by emillon** [comment] 2023-02-21 16:04
(thanks for reporting this! this means that somebody reads these docs :) )

**Closed by emillon** 2023-02-21 16:04 UTC

**Comment by toots** [comment] 2023-02-21 16:06
> (thanks for reporting this! this means that somebody reads these docs :) )

All the time! Thanks for the quick fix!
