### ISSUE TITLE
opam file generation and test selection 

### ISSUE THREAD

**Issue by Ninjapouet** [ocaml/dune#3792] opened 2020-09-15 10:42 UTC
Hi,

I have the following situation and I wonder if I missed something or if it needs some feature request. In a repository with the following layout:
- a lib package definition (A-lib)
- a binary package definition (A-bin) depending on (A-lib)
- Tests definitions for the lib using .expected stuff and cram test for the binary package.
Alas, I've never figured out how to tell dune that @runtest should run the corresponding package test suite.

Using the (deps (package A-bin)) in (cram) doesn't work for a clean opam install A-lib -t complains about missing A-bin. I tried to add (depends (A-bin :with-test)) in A-lib package definition, thinking that running test may be postponed after package installation, but dune complains with a circular dependency A-lib -> A-bin -> A-lib.

I tried to play with the (enable_if) of the (cram) stanza but it seems to be not expressive enough to specify the target package (or i don't understand how at least).

I see that I can write some .opam.template overriding the with-test build command to run specific runtest command on some sub directories to split the tests properly but I feel uncomfortable to write .opam files manually with a build system that can generate them...

Of course, I can split the repository in two but again, i feel that's not very clever as the two packages share stuff.

Do you have any clean solution to this issue or does it need some feature request ?

**Comment by Ninjapouet** [comment] 2020-09-16 07:21
After some testing, the opam.template seems to do the job but this is, imho, not as clean as giving tests/cram stanza a package relation so that @runtest could launch only the required tests with the -p option.

**Comment by rgrinberg** [comment] 2020-10-01 21:24
Thanks for the report. This is indeed an annoying problem and it should be possible to add a `package` field to `cram` tests.

@jeremiedimino I've looked into implementing this and this somewhat awkward. The problem is that we interpret:

```
(cram
 (package foo)
 (applies_to ..))
```

We want all tests selected with `applied_to` to be marked as part of `foo`. However, package filtering is done at the stanza level in `gen_rules`, while this feature requires us to know the list of packages in `-p` when evaluating the cram stanza rule.

The only way I see to implement this is to pass down the list of packages specified in `--only-packages` to `Cram_rules.rules`. While that is easy, it seems like this will complicate the semantics of `--only-packages` to more than just filtering of stanzas.

**Comment by jeremiedimino** [comment] 2020-10-05 11:14
Indeed. So, for the future we have a good story: the one package per directory model. It's a pretty simple model that will cover all stanzas.

In the meantime, either we can find a clear enough semantic for `--only-packages` that covers `cram`, or we just wait for the one package per dir and do nothing for now.

**Comment by rgrinberg** [comment] 2020-10-05 17:31
Sure, but I think we should raise the urgency of that proposal. The current situation is that running your tests in opam and cram are mutually exclusive.

**Comment by jeremiedimino** [comment] 2020-10-06 10:18
Well, I wouldn't say urgent as Cram is a brand new feature. But agreed that we are feeling the need for clearer handling of multi-package repos more and more.

There is another issue to solve before cram can truly be used in multi-package repos: a `(package xx)` dependency doesn't work with package `xx` is installed rather than present in the workspace. (cf https://github.com/ocaml/dune/issues/3418).

But back to this discussion. I kind of remember that the PR to add supports for private installed libraries also break the assumption that `--only-packages` only filters stanzas. i.e. it needs to `library` stanza for private installed libraries into something that register the name translation. Is that right? If that's the case, then we are already departing from the current simple semantic of `--only-packages` and we don't need to bother here. We just need to find a new semantic for this option and adapt the doc. Let me give it a try:

`--only-packages SET` disables stanzas that have belong to package that is not part of `SET`. The items described by such stanzas will no longer be accessible during the build. For instance, a public library that is part of a package outside of `SET` will not be built and must be installed on the system if it is required. Similarly, a tests that is part of such a package will not be built or executed by Dune.

**Comment by rgrinberg** [comment] 2021-01-11 20:32
> There is another issue to solve before cram can truly be used in multi-package repos: a (package xx) dependency doesn't work with package xx is installed rather than present in the workspace

Indeed this is quite annoying and we should really address this for 3.0.

The workaround you propose sounds good to me.

**Closed** 2021-01-13 17:24 UTC
