### ISSUE TITLE
Allow to add object files to a library

### ISSUE THREAD

**Issue by Chris00** [ocaml/dune#788] opened 2018-05-22 11:09 UTC
In addition to specify C and C++ files, it would be useful to be able to list _object files_ used to build a library.  This is useful for example to add code coming from a FORTRAN library (wrapped for OCaml in a C stub file).

**Comment by rgrinberg** [comment] 2020-09-18 23:36
This is a duplicate of #803. Closing this issue as the other one has more discussion.

**Closed by rgrinberg** 2020-09-18 23:36 UTC
