### ISSUE TITLE
support recursive enable_if in tests

### ISSUE THREAD

**Issue by samoht** [ocaml/dune#6132] opened 2022-09-07 15:15 UTC
Using an `enabled_if` library in a test stanza protected by an `enabled_if` is not supported while it is for tests.

For instance https://github.com/ocaml-multicore/eio/blob/6a85b668a7cf75efcd304cba0fadabc0e2866b03/lib_eio_linux/tests/dune#L25-L30

On macOS This will fail with:

```
❯ dune build
File "lib_eio_linux/tests/dune", line 30, characters 21-30:
30 |  (libraries alcotest eio_linux))
                          ^^^^^^^^^
Error: Library "eio_linux" in _build/default/lib_eio_linux is hidden
(unsatisfied 'enabled_if').
-> required by _build/default/lib_eio_linux/tests/test.bc
-> required by alias lib_eio_linux/tests/all
-> required by alias default
```

Changing the `test` into `executable` works.

**Comment by emillon** [comment] 2022-09-09 12:52
Duplicate of #5505

**Closed** 2022-10-19 03:29 UTC
