### ISSUE TITLE
Random `rmdir, not empty` error on concurrent `dune exec` calls

### ISSUE THREAD

**Issue by smondet** [ocaml/dune#4904] opened 2021-09-07 19:26 UTC
## Expected Behavior

`dune exec` commands do not fail randomly even if they are called concurrently.

## Actual Behavior

Once in a while one or more of the `dune exec` calls seem to fail with:

```
Error: rmdir: _build/default/.dune: Directory not empty
```

## Reproduction

Hard to reproduce as it seem quite random, have an application and run concurrent `dune exec my-app.exe`.

## Specifications

- Version of `dune` (output of `dune --version`): 2.9.0
- Version of `ocaml` (output of `ocamlc --version`): 4.12
- Operating system (distribution and version): Ubuntu

**Comment by ejgallego** [comment] 2021-09-07 21:47
AFAICT `dune exec` is not reentrant, I seem to recall there was a bug open about it.

We workaround that by using `flock`

**Comment by rgrinberg** [comment] 2022-01-24 06:37
Duplicate of https://github.com/ocaml/dune/issues/236

File locking is indeed the solution.

**Closed by rgrinberg** 2022-01-24 06:37 UTC
Labels: bug
