### ISSUE TITLE
`jbuilder runtest -p mysubpkg` tries to run all tests

### ISSUE THREAD

**Issue by mjambon** [ocaml/dune#807] opened 2018-05-26 07:43 UTC
Not sure if this may be related to https://github.com/ocaml/dune/issues/568
I'm using jbuilder 1.0+beta20.

We're having this problem right now in the atd repo, which includes 4 opam packages (atd, atdgen-runtime, atdgen, atdj):
```
$ git clone https://github.com/mjambon/atd.git
$ cd atd
$ opam remove atd atdgen-runtime atdgen   # opam packages provided by this git repo
$ jbuilder build -p atd
$ jbuilder runtest -p atd
Error: Program atdgen not found in the tree or in PATH (context: default)
...
```
What happens is that the build command with `-p atd` builds only the atd package, but the runtest command apparently ignores the `-p atd` option and tries to run the tests for all packages; this fails because we built only the `atd` package.

Workaround:
```
$ (cd atd && jbuilder runtest)
```
but I don't know how to specify this in an opam file:
```
build-test: [
  [???]
]
```

**Comment by rgrinberg** [comment] 2018-05-26 10:08
I think the issue is that we don't have `(package <name>)` fields on our alias stanzas.

**Comment by diml** [comment] 2018-06-02 10:50
IIUC the solution is to add a few `(package <name>)` fields in the runtest aliases of atd. Should we close this issue then?

**Comment by rgrinberg** [comment] 2018-06-02 10:57
Yup. I will make fix atd.

**Closed by rgrinberg** 2018-06-02 10:57 UTC
