### ISSUE TITLE
Use Dune to build a C library

### ISSUE THREAD

**Issue by Niols** [ocaml/dune#1832] opened 2019-02-12 17:09 UTC
Hello there,

I'm trying to pass [Morbig](https://github.com/colis-anr/morbig) under Dune. The problem I face is that Morbig provides a C API. For now, the compilation is done using OCamlBuild and [a Makefile to merge all the different `.a` together](https://github.com/colis-anr/morbig/blob/30312745e91c330ce8c7f20187f745a01abe7400/src/Makefile#L31).

Dune builds a `.a` for the lib (`morbig.a`). It's easy to add a `(c_name cstub)` field that will cause Dune to build a `libmorbig_stub.a` file. But then, is there a way to tell Dune that what I would like is a `.a` file containing both these libraries but also all the dependencies of the project and `libasmrun.a` (or `libocamlrun.a`)?

I tried playing with ocamlfind's `-linkpkg` option, ocamlopt's `-linkall` option but without success. Is there a way to tell Dune to bundle *everything* in the generated `morbig.a` file? Or a way to create that file with a custom rule?

Thank you,
-- Niols

**Comment by diml** [comment] 2019-02-13 07:34
This looks like a use case of `(modes object)` (cf https://dune.readthedocs.io/en/latest/dune-files.html#linking-modes). Have you tried something like this:

```scheme
(executable
 (name foo)
 (libraries a b c)
 (modes object))
```

? This will produce a `foo.o` object file that you can link in C applications.

**Comment by Niols** [comment] 2019-02-13 10:06
That is just **brilliant**. I didn't think of that but it works so well…

I just have one small question remaining then: What if I have a C stubs file that I would like included in this executable? I can't put a `(c_names cstubs)` field in the `(executable ...)` stanza. I have tried putting this `(c_names ...)` field in a library upon which my executable depends, but without success. I can do it by hand by adding a custom rule using `ar`, but there might be a better way. Is there?

**Comment by diml** [comment] 2019-02-13 11:16
Glad it works :)

Yeah, currently `c_names` is not supported on executables, although it could be. Putting it on a library and depending on that library should work, what is the issue?

**Comment by Niols** [comment] 2019-02-13 11:31
When building the library `morbig` with stubs, I get a `libmorbig_stub.a` file containing the stubs. (Actually, I also get a `morbig.a` file containing Morbig without its dependencies and without the stubs.)

Then, when building the executable `libmorbigc` with `(modes object)` and `(library morbig)` I get a nice `libmorbigc.o` containing everything except what is in this `libmorbig_stub.a` file.

For now, I added an `ar` rule after that to put these two files together into what I want, but I was expecting stubs to end up in the `morsmall.a` and then the `libmorbigc.o`. Did I do something wrong?

**Comment by diml** [comment] 2019-02-13 12:04
Hmm, `libmornig_stub.a` should indeed end up in `libmornigc.o`. This looks like a bug. Not sure if it is in dune or in ocaml though. What version of ocaml are you using? I remember seeing related fixes recently.

For the record, `morbig.a` contains the compiled OCaml code, while `libmirnog_stub.a` contains the compiled C stubs.  I suppose the two could be merged, however that's how the OCaml tools work, so it's easier for dune to follow this method.

**Comment by Niols** [comment] 2019-02-13 15:35
> Hmm, `libmornig_stub.a` should indeed end up in `libmornigc.o`. This looks like a bug. Not sure if it is in dune or in ocaml though. What version of ocaml are you using? I remember seeing related fixes recently.

I'm using 4.07.1. Should I try with the new OCaml 4.08 beta?

> For the record, `morbig.a` contains the compiled OCaml code, while `libmirnog_stub.a` contains the compiled C stubs. I suppose the two could be merged, however that's how the OCaml tools work, so it's easier for dune to follow this method.

Yeah, I was expecting them to be merged, but why not. However, this should end up in the final `.o`.

**Comment by diml** [comment] 2019-02-13 15:39
> I'm using 4.07.1. Should I try with the new OCaml 4.08 beta?

Yes, that would help to identify where the issue lies.

**Comment by Niols** [comment] 2019-02-13 16:39
Hum, I thought it would be in OPAM by now, but apparently not. I have tried on 4.07.0 and 4.04.2 though, and I get the same thing. I'll produce a minimal example to reproduce this. Maybe I'm just doing things the wrong way.

**Comment by diml** [comment] 2019-02-18 11:04
A minimal example would be helpful. We could add it as a reproduction case in dune.

**Comment by Niols** [comment] 2019-02-18 15:42
I tried creating that minimal example:

[dune-1832-minimal-example.zip](https://github.com/ocaml/dune/files/2876402/dune-1832-minimal-example.zip)

Does that look OK?

**Comment by diml** [comment] 2019-02-18 16:32
I just tried it on my laptop and it seems to work: `make` succeeds and prints `Hello, world!`

**Comment by Niols** [comment] 2019-02-19 08:41
Hum, that's because that was the workaround for the issue. Here is an archive with both the broken version and a workaround:
[dune-1832-minimal-example.zip](https://github.com/ocaml/dune/files/2879117/dune-1832-minimal-example.zip)

**Comment by diml** [comment] 2019-02-20 08:21
I'm closing this issue since there is nothing to do in dune. It'd be good to document this somewhere though

**Closed by diml** 2019-02-20 08:21 UTC

**Comment by Niols** [comment] 2019-02-20 08:50
Thank you, that works indeed! I just tried and it apparently works to put the external in `CAPI.ml` also. I imagine that it is coming from OCaml that detects an unused dependency and drops it?

There is indeed no issue in Dune. Thank you very much for your help on this!

- Should I open a feature request to have `(c_names ...)` available in `(executable ...)`?
- I'm not sure how to contribute to documentation but I can try to add this somewhere if you'd like.

**Comment by diml** [comment] 2019-02-20 09:19
No problem, glad it's sorted. At this level, I believe it's `ld` that's dropping the dependency. OCaml might only drop OCaml compilation units (.cmo and .cmx files).

> Should I open a feature request to have (c_names ...) available in (executable ...)?

Seems good to me

> I'm not sure how to contribute to documentation but I can try to add this somewhere if you'd like.

That would be nice. The documentation is in the `doc/` folder, in restructured text format. For instance the documentation for `(mode object)` is in `doc/dune-files.rst` (you can search for `linking modes` in this file). You can simply make a PR to add something there. Once it's merged in master, `dune.readthedocs.io` is automatically updated.

**Comment by Niols** [comment] 2019-02-20 09:40
> > I'm not sure how to contribute to documentation but I can try to add this somewhere if you'd like.
> 
> That would be nice. The documentation is in the `doc/` folder, in restructured text format. For instance the documentation for `(mode object)` is in `doc/dune-files.rst` (you can search for `linking modes` in this file). You can simply make a PR to add something there. Once it's merged in master, dune.readthedocs.io is automatically updated.

OK, I'll do this! :-)

**Comment by Niols** [comment] 2019-02-27 23:57
Hum, an unexpected side-effect of putting the `(c_names ...)` field in the main library stanza is that it broke the bytecode compilation of libraries using my tool. I added an additional artificial library to fix this, but this is a bit sad. The `(c_names ...)` field in `(executable ...)` would be nice (but I haven't found the time to read the other issue yet).

**Comment by jonathan-laurent** [comment] 2020-07-22 17:02
I found the example shared by @Niols very useful.
I am sharing an updated version that works with Dune 2.5: [binding-example.zip](https://github.com/ocaml/dune/files/4961337/binding-example.zip)

> Thanks, I found the issue. It's very subtle, I have been bitten by this in the past as well: when `CAPI.exe.o` is linked, there is nothing that references `cstubs.o` which is part of `liblib_stubs.a`, so the linker decides to just drop it :/
> 
> To prevent that, you can add a reference in the ml code: add a dummy external in `cstubs.c` and declare it in `lib.ml`. That will cause `cstubs.o` to be linked in.

@jeremiedimino This does not seem to be necessary anymore. Was there any improvement that was made on Dune's side which removed the need for such a trick?

**Comment by nojb** [comment] 2020-07-22 17:47
xref #3641 (not the same issue, but related)

**Comment by jeremiedimino** [comment] 2020-07-27 10:25
@jonathan-laurent the only change I can think of is the issue pointed by @nojb. However, we did change a bit the code in this part of the world some time ago, so maybe this changed as a side-effect  ¯\_(ツ)_/¯

If you are curious about getting to the bottom of this, you can play with `dune rules`. `dune rules -rm <target>` will print a makefile that can build the target from scratch. If you diff it between the version of dune where it didn't work and the version of dune where it worked, you might be able to spot the difference that made it work.
