### ISSUE TITLE
Build coverage fails on cstruct

### ISSUE THREAD

**Issue by ElectreAAS** [ocaml/dune#10856] opened 2024-08-28 15:43 UTC
I've tried to build several highly depended-upon packages with the new package management features to improve coverage, and here's an interesting one:

Note: according to check.ci.ocaml.org, `cstruct.6.2.0` has 4340 reverse dependencies, which is almost the maximum.

```
---> Building package n°12: package "cstruct.6.2.0":
Successfully extracted to /tmp/pkg-coverage-9df431-builder/cstruct.6.2.0
Solution for dune.lock:
- afl-persistent.1.4
- alcotest.1.8.0
- astring.0.8.5
- async.v0.16.0
- async_kernel.v0.16.0
- async_rpc_kernel.v0.16.0
- async_unix.v0.16.0
- base.v0.16.3
- base-bigarray.base
- base-bytes.base
- base-threads.base
- base-unix.base
- base_bigstring.v0.16.0
- base_quickcheck.v0.16.0
- bin_prot.v0.16.0
- cmdliner.1.3.0
- conf-bash.1
- core.v0.16.2
- core_kernel.v0.16.0
- core_unix.v0.16.0
- cppo.1.6.9
- crowbar.0.2.1
- csexp.1.5.2
- dune-configurator.3.16.0
- expect_test_helpers_core.v0.16.0
- fieldslib.v0.16.0
- fmt.0.9.0
- host-arch-x86_64.1
- host-system-other.1
- int_repr.v0.16.0
- jane-street-headers.v0.16.0
- jst-config.v0.16.0
- lwt.5.7.0
- lwt_ppx.2.1.0
- num.1.5-1
- ocaml.4.14.2
- ocaml-base-compiler.4.14.2
- ocaml-compiler-libs.v0.12.4
- ocaml-config.2
- ocaml-migrate-parsetree.2.4.0
- ocaml-options-vanilla.1
- ocaml-syntax-shims.1.0.0
- ocaml_intrinsics.v0.16.1
- ocamlbuild.0.15.0+dune
- ocamlfind.1.9.6+dune
- ocplib-endian.1.2
- ounit.2.2.7
- ounit2.2.2.7
- parsexp.v0.16.0
- ppx_assert.v0.16.0
- ppx_base.v0.16.0
- ppx_bench.v0.16.0
- ppx_bin_prot.v0.16.0
- ppx_cold.v0.16.0
- ppx_compare.v0.16.0
- ppx_custom_printf.v0.16.0
- ppx_derivers.1.2.1
- ppx_disable_unused_warnings.v0.16.0
- ppx_enumerate.v0.16.0
- ppx_expect.v0.16.0
- ppx_fields_conv.v0.16.0
- ppx_fixed_literal.v0.16.0
- ppx_globalize.v0.16.0
- ppx_hash.v0.16.0
- ppx_here.v0.16.0
- ppx_ignore_instrumentation.v0.16.0
- ppx_inline_test.v0.16.1
- ppx_jane.v0.16.0
- ppx_let.v0.16.0
- ppx_log.v0.16.0
- ppx_module_timer.v0.16.0
- ppx_optcomp.v0.16.0
- ppx_optional.v0.16.0
- ppx_pipebang.v0.16.0
- ppx_sexp_conv.v0.16.0
- ppx_sexp_message.v0.16.0
- ppx_sexp_value.v0.16.0
- ppx_stable.v0.16.0
- ppx_stable_witness.v0.16.0
- ppx_string.v0.16.0
- ppx_tydi.v0.16.0
- ppx_typerep_conv.v0.16.0
- ppx_variants_conv.v0.16.0
- ppxlib.0.33.0
- protocol_version_header.v0.16.0
- re.1.11.0
- seq.base
- sexp_pretty.v0.16.0
- sexplib.v0.16.0
- sexplib0.v0.16.0
- spawn.v0.15.1
- splittable_random.v0.16.0
- stdio.v0.16.0
- stdlib-shims.0.3.0
- textutils.v0.16.0
- textutils_kernel.v0.16.0
- time_now.v0.16.0
- timezone.v0.16.0
- topkg.1.0.7
- typerep.v0.16.0
- uutf.1.0.3
- variantslib.v0.16.0
Error:                              
_build/.sandbox/d4d1b9ebc14f40c477c5ba21cfb1d070/_private/default/.pkg/afl-persistent/source/config.sh	2024-01-31
15:11:06: No such file or directory
-> required by _build/_private/default/.pkg/afl-persistent/target/cookie
-> required by - package crowbar
```

I don't really understand this error beyond "there's a file missing", but that's what this issue is for

**Comment by Leonidas-from-XIV** [comment] 2024-08-29 14:09
I've looked into it and the issue is with `afl-persistent`. This is happening because the `extra-source` patch tries to patch the `config.sh` in the `build` step but somehow it fails despite both the patch and the `config.sh` being in the unpacked source at the right spot. Removing it fixes the build but obviously this isn't the right approach, so there's something about the `patch` action that needs fixing.

**Comment by Leonidas-from-XIV** [comment] 2024-08-29 14:27
Ok, so turns out the issue funnier than I expected, because if one looks closely then the issue is not that `config.sh` is missing, the error message says that `config.sh	2024-01-31 15:13:00` is missing aka we are misinterpreting the date in the format for the filename, aka we don't support the patch format.

I did a small test and GNU `patch` applies the patch just fine, so our options are:

  * Implement this format
  * Change the patch format of the afl-persistent package

**Comment by ElectreAAS** [comment] 2024-08-29 14:30
For reference, the patch originates here https://github.com/ocaml/opam-repository/pull/25144, and the patch itself is archived here https://github.com/ocaml/opam-source-archives/blob/main/patches/afl-persistent/config.patch

**Comment by Leonidas-from-XIV** [comment] 2024-08-29 14:43
Upon further investigation we already use `patch`, it's just that we determine the file names to be patched and that code assumes everything after (`--- a/`/`--- `) is a file name. Should be an easy fix.

**Comment by Leonidas-from-XIV** [comment] 2024-09-06 13:50
I think with #10865 merged this should thus be solved.

**Closed by Leonidas-from-XIV** 2024-09-06 13:50 UTC
Labels: package management, package management build failures
