### ISSUE TITLE
Support for `or` in opam dependencies generation

### ISSUE THREAD

**Issue by toots** [ocaml/dune#6284] opened 2022-10-21 16:55 UTC
Reading from the doc, it looks like the `dune-project` support for generating `opam` files does not support top-level `or` (`|` in opam) combinators for dependencies:
```
"depends": [
  "foo" | "bla"
]
```
The template file is not really useful for this either.

**Comment by emillon** [comment] 2022-11-02 14:22
duplicate of #5815

**Comment by toots** [comment] 2022-11-02 14:37
Sorry about that!

**Closed** 2022-11-02 15:26 UTC

**Comment by emillon** [comment] 2022-11-02 15:51
Sorry, "duplicate of XXX" is a bit of an unfriendly message but I don't think there's another way to set this piece of metadata :)

**Comment by toots** [comment] 2022-11-02 16:46
No pb!
