### ISSUE TITLE
[Pkg] Pinning tar file

### ISSUE THREAD

**Issue by maiste** [ocaml/dune#11130] opened 2024-11-18 16:42 UTC
For feature parity, when pinning URLs in opam, you can use a `tar.gz` file. With Dune package management, it will complain when trying to do so. For example, with `opam-tailwind`, the dune version fails:
```lisp
(pin
 (url
   "https://github.com/tmattio/opam-tailwindcss/archive/e5bb6361a50c7cc5cad802311e609336583ca08f.tar.gz")

```
but the opam one succeed:
```opam
pin-depends: [
  ["tailwindcss.dev" "https://github.com/tmattio/opam-tailwindcss/archive/e5bb6361a50c7cc5cad802311e609336583ca08f.tar.gz"]
]
```

## Expected Behavior

It should succeed by downloading, unzipping, and building the `tar.gzip` file.

## Actual Behavior

It fails to determine the location.

```
File "dune-project", line 62, characters 3-104:                      
62 |    "https://github.com/tmattio/opam-tailwindcss/archive/e5bb6361a50c7cc5cad802311e609336583ca08f.tar.gz")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Could not determine location of repository
https://github.com/tmattio/opam-tailwindcss/archive/e5bb6361a50c7cc5cad802311e609336583ca08f.tar.gz
Hint: Specify either a file path or git repo via SSH/HTTPS
````

**Comment by rgrinberg** [comment] 2024-11-20 23:08
Your dune version incorrectly specifies the url. A git url is expected to be fetched with git. Your url should drop the `git+` prefix and match the opam url

**Comment by maiste** [comment] 2024-11-21 09:30
Indeed, I push the wrong version, sorry!

 I have updated my issue description with the correct version. When trying with only HTTPS, it doesn't seem to be able to resolve the URL (this time I tried in my browser, and it downloads the correct file).

**Comment by rgrinberg** [comment] 2024-11-24 00:07
Thanks for clarifying. This is actually a duplicate of https://github.com/ocaml/dune/issues/10121. PR's to fix it are welcome.

**Closed by rgrinberg** 2024-11-24 00:07 UTC
Labels: enhancement, package management
