### ISSUE TITLE
Can't build bc version with dune lang 2.0

### ISSUE THREAD

**Issue by vsiles** [ocaml/dune#3017] opened 2020-01-09 10:06 UTC
## Expected Behavior
I'm trying to build the byte code version of the following dummy project:
- dune-project: `(lang dune 2.0)`
- dune: `(executable (name test))`
- test.ml `let _ = print_endline "test"`

Running both `dune build test.exe` and `dune build test.bc` should work.

## Actual Behavior
Running `dune build test.exe` works correctly but `dune build test.bc` returns:
```
$ dune build test.bc
Error: Don't know how to build test.bc
Hint: did you mean test.ml?
```

## Reproduction
See dummy project above and change the lang version from 1.9 to  2.0 and back to see that 1.9 works but 2.0 doesnt.

## Specifications

- Version of `dune`: `opam list | grep dune` returns 2.1.1. `dune --version` returns `2.1.1`
- Version of `ocaml`: 4.08.0
- Operating system:  macos Catalina

## Additional information 

- Link to gist with verbose output (run `dune` with the `--verbose` flag):

**Comment by diml** [comment] 2020-01-09 10:41
This is due to a change of the defaults in `(lang dune 2.x)`. You now need to explicitly ask Dune to request the bytecode executable to be built by adding `(modes byte exe)` to the `executable` stanza. The rational for this change is as follow:


- with `(lang dune 2.x)`, the default is to build `@all` rather than `@install`. It was generally accepted that `@install` was a bad default and `@all` is better
- `@all` will build everything that can be built, in particular it will build all modes for executables
- most users don't care about bytecode executables and only building the `.exe` is enough. FTR, when native compilation is not available the `.exe` is a self-contained bytecode executable
- with `(modes byte exe)`, `dune build` builds both the `.exe` and the `.bc`

Considering all this, we decided to change the default for the `modes` field of executables from `(modes byte exe)` to `(modes exe)`. That will save time in general by not building `.bc` unless explicitly requested by the user.

**Comment by diml** [comment] 2020-01-09 10:41
Closing since this is not a bug.

**Closed by diml** 2020-01-09 10:41 UTC

**Comment by vsiles** [comment] 2020-01-09 10:52
Thank you for the explanation. Could I suggest to write this in the doc ? When one searches for `bc` in the doc, there is a single occurrence stating that `dune build foo.bc` is the way to go.

**Comment by diml** [comment] 2020-01-09 11:23
That seems good yes. Where would you put it in the doc?

**Comment by vsiles** [comment] 2020-01-09 11:29
I would put it in the https://dune.readthedocs.io/en/stable/quick-start.html section, next to the hello world

**Comment by diml** [comment] 2020-01-09 11:47
That seems like a good place indeed. Do you want to do a PR to add that? :)

**Comment by vsiles** [comment] 2020-01-09 11:49
I'll try to find some time next week to do that, it's going to bit difficult this week.

**Comment by ygrek** [comment] 2020-01-10 15:12
Is it possible to have a target that builds @all in bytecode while allowing to build exe on demand? Our usecase is bytecode build by default for development because it is faster and native build for release.

**Comment by diml** [comment] 2020-01-13 16:42
Yes, that seems reasonable and not very difficult. Basically, we could have an option so that all native OCaml binaries are instead built as standalone bytecode executables (i.e. with `-output-complete-exe`). This way you would still get the same `.exe` files and all existing rules would work the same, except that `.exe` would be bytecode programs rather than native ones.

For libraries, we would need to not attach .cmxa files to `@all`.

Could you open a feature request for this?

**Comment by ygrek** [comment] 2020-01-15 09:41
I am ok with keeping explicit .bc extension for bytecode targets, I think it will be less confusing, but in any case this is orthogonal. 
My comment was about this new assumption :
> most users don't care about bytecode executables and only building the .exe is enough. FTR, when native compilation is not available the .exe is a self-contained bytecode executable

and it doesn't hold in our case - we care to be able to build both bytecode and native executables, but we don't want to list all targets when invoking dune, but rather have `@all` `@all.bytecode` `@all.native` targets or smth like this. I will open a feature request about that.
