### ISSUE TITLE
per_module breaks .merlin output

### ISSUE THREAD

**Issue by dra27** [ocaml/dune#1212] opened 2018-09-02 07:50 UTC
For the following dune file:

```
(library
  (name       Mercury)
  (preprocess (per_module ((pps ppx_pgsql) Mercury)))
  (modules    Mercury)
  (libraries  pgocaml))
```

Merlin doesn't load the PPX for `Mercury.ml`. If I change the `preprocess` stanza to just `(pps ppx_pgsql)` then `.merlin` gains the required:

```
FLG -ppx '/home/dra/ocamldefang/_build/default/.ppx/ppx_pgsql/ppx.exe --as-ppx --cookie '\''library-name="Mercury"'\'''
```

**Comment by rgrinberg** [comment] 2018-09-02 09:58
This is a known issue. We could improve the approximation of the merlin command by taking the union of ppx preprocessors, but we've been kind of dragging our feet on this stuff as we'd really like to see this issue fixed once and for all. Feel free to add a workaround for this for now if it's blocking you.

@trefis do we have an ETA on the new merlin interface?

**Comment by gares** [comment] 2019-04-15 07:40
Is there an open issue in the merlin issue tracker for this specific need? I could not find it, maybe we should add one?

**Comment by diml** [comment] 2019-04-15 13:35
opening such an issue makes sense

**Comment by trefis** [comment] 2020-09-23 09:13
The new merlin interface is released, and I believe @voodoos is working on (and might already be done) improving this particular point on the dune side.

**Comment by voodoos** [comment] 2021-01-14 15:26
This should be fixxed in Dune 2.8. If it is not don't hesitate to warn us.

**Comment by gares** [comment] 2021-01-16 08:51
Great thanks!

**Comment by gares** [comment] 2021-01-25 13:10
Hello, I tried to use this new feature but I can't get it to work.

This is my attempt: https://github.com/LPCIC/elpi/pull/91 but if I open anything in src/*.ml then I don't get the pre-processing, e.g. data.ml is not getting `[@@deriving]` executed...

I'm on
```
gares@ollypat:~/LPCIC/elpi$ opam list | grep serv
ocaml-lsp-server         1.4.0       LSP Server for OCaml
gares@ollypat:~/LPCIC/elpi$ opam list | grep dune
dune                     2.8.2       Fast, portable, and opinionated build system
dune-build-info          2.8.2       Embed build informations inside executable
dune-configurator        2.8.2       Helper library for gathering system configuration
dune-private-libs        2.6.2       Private libraries of Dune
```
and I'm using vscode with https://marketplace.visualstudio.com/items?itemName=ocamllabs.ocaml-platform just installed (I had the reason thing before, since I like the syntax highlighting better, but I guess I have to switch now).

**Comment by gares** [comment] 2021-01-25 13:13
Side note: I had a single runtime.ml file and 2 copy_file directives, but apparently this does not work anymore, so I did make a symlink. I'm OK with that, just wanted to point out the change of behavior.

**Comment by voodoos** [comment] 2021-01-25 15:10
@gares, thanks for trying this out, I will have a look when I have time.

It would be very useful if you could build a small, self-contained, reproduction !

**Comment by gares** [comment] 2021-01-25 15:34
Hum, I can help debug but I don't know how to start. Maybe you can give a hint.
Is there a way to know which pp line is being used by ocamllsp? does it log?

**Comment by voodoos** [comment] 2021-01-25 15:44
You can ask Dune to print the configurations for a source folder by calling 
`dune ocaml-merlin --dump-config="$(pwd)"`
from this source folder. (or from elsewhere in the project with the correct path)

There is also the Merlin counterpart (i don't know if ocamllsp has a similar feature, @rgrinberg ?):
`ocamlmerlin single dump-configuration -filename somefile.ml <somefile.ml | jq `

And for reference there is a case in Dune test-suite for per-module config:
https://github.com/ocaml/dune/tree/main/test/blackbox-tests/test-cases/merlin/per-module-pp.t

**Comment by gares** [comment] 2021-01-25 16:07
My dune file has
```
  (preprocess (per_module
    ((action (run %{project_root}/ppxfindcache/ppxfindcache2.exe %{input-file}
                    --cache-file %{dep:.ppcache/API.ml}
                    --cache-file %{dep:.ppcache/API.mli}
                    --cache-file %{dep:.ppcache/util.ml}
                    --cache-file %{dep:.ppcache/util.mli}
                    --cache-file %{dep:.ppcache/ast.ml}
                    --cache-file %{dep:.ppcache/ast.mli}
                    --cache-file %{dep:.ppcache/data.ml}
                    --cache-file %{dep:.ppcache/compiler.ml}
                    --cache-file %{dep:.ppcache/compiler.mli}))
              API ast data compiler)
```
and the dump (for `Data`) is
```
Data
((EXCLUDE_QUERY_DIR)
 (B /home/gares/.opam/4.07.1/lib/camlp5)
 (B /home/gares/.opam/4.07.1/lib/ocaml)
 (B /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (B /home/gares/.opam/4.07.1/lib/re)
 (B /home/gares/.opam/4.07.1/lib/re/str)
 (B /home/gares/.opam/4.07.1/lib/result)
 (B /home/gares/.opam/4.07.1/lib/seq)
 (B /home/gares/LPCIC/elpi/_build/default/src/.elpi.objs/byte)
 (B
  /home/gares/LPCIC/elpi/_build/default/trace/runtime/.trace_ppx_runtime.objs/byte)
 (S /home/gares/.opam/4.07.1/lib/camlp5)
 (S /home/gares/.opam/4.07.1/lib/ocaml)
 (S /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (S /home/gares/.opam/4.07.1/lib/re)
 (S /home/gares/.opam/4.07.1/lib/re/str)
 (S /home/gares/.opam/4.07.1/lib/result)
 (S /home/gares/.opam/4.07.1/lib/seq)
 (S /home/gares/LPCIC/elpi/src)
 (S /home/gares/LPCIC/elpi/trace/runtime)
 (FLG (-open Elpi__ -linkall)))
```

**Comment by gares** [comment] 2021-01-25 16:08
I was expecting to see `FLG (-pp .../ppxfindcache/ppxfindcache2.exe ....)`, which is not there, and explains why I don't get pre-processing in vscode.

**Comment by gares** [comment] 2021-01-25 16:10
Note that directories about the ppx I link in `ppxfindcache2.exe ` are there:
```
 (B /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (B
  /home/gares/LPCIC/elpi/_build/default/trace/runtime/.trace_ppx_runtime.objs/byte)
```

**Comment by rgrinberg** [comment] 2021-01-25 16:32
> I was expecting to see FLG (-pp .../ppxfindcache/ppxfindcache2.exe ....), which is not there, and explains why I don't get pre-processing in vscode.

This used to be supported in .merlin files. So this seems like a  regression indeed.

**Comment by voodoos** [comment] 2021-01-26 09:34
@gares, can you post the complete output of the configuration dump ?
I am wondering if the `(FLG (-pp` directives are also absent from the other modules selected in the `per_module` directive.

(In the [Dune test case](https://github.com/ocaml/dune/tree/main/test/blackbox-tests/test-cases/merlin/per-module-pp.t) for the `per_module` merlin config which is simpler but similar to your project the `-pp` flag is added as expected.)

**Comment by gares** [comment] 2021-01-26 10:28
It is present for the parser, which calls camlp5.
```
gares@ollypat:~/LPCIC/elpi/src$ dune ocaml-merlin --dump-config="$(pwd)"
Entering directory '/home/gares/LPCIC/elpi'
Util
((EXCLUDE_QUERY_DIR)
 (B /home/gares/.opam/4.07.1/lib/camlp5)
 (B /home/gares/.opam/4.07.1/lib/ocaml)
 (B /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (B /home/gares/.opam/4.07.1/lib/re)
 (B /home/gares/.opam/4.07.1/lib/re/str)
 (B /home/gares/.opam/4.07.1/lib/result)
 (B /home/gares/.opam/4.07.1/lib/seq)
 (B /home/gares/LPCIC/elpi/_build/default/src/.elpi.objs/byte)
 (B
  /home/gares/LPCIC/elpi/_build/default/trace/runtime/.trace_ppx_runtime.objs/byte)
 (S /home/gares/.opam/4.07.1/lib/camlp5)
 (S /home/gares/.opam/4.07.1/lib/ocaml)
 (S /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (S /home/gares/.opam/4.07.1/lib/re)
 (S /home/gares/.opam/4.07.1/lib/re/str)
 (S /home/gares/.opam/4.07.1/lib/result)
 (S /home/gares/.opam/4.07.1/lib/seq)
 (S /home/gares/LPCIC/elpi/src)
 (S /home/gares/LPCIC/elpi/trace/runtime)
 (FLG (-open Elpi__ -linkall)))
Runtime_trace_on
((EXCLUDE_QUERY_DIR)
 (B /home/gares/.opam/4.07.1/lib/camlp5)
 (B /home/gares/.opam/4.07.1/lib/ocaml)
 (B /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (B /home/gares/.opam/4.07.1/lib/re)
 (B /home/gares/.opam/4.07.1/lib/re/str)
 (B /home/gares/.opam/4.07.1/lib/result)
 (B /home/gares/.opam/4.07.1/lib/seq)
 (B /home/gares/LPCIC/elpi/_build/default/src/.elpi.objs/byte)
 (B
  /home/gares/LPCIC/elpi/_build/default/trace/runtime/.trace_ppx_runtime.objs/byte)
 (S /home/gares/.opam/4.07.1/lib/camlp5)
 (S /home/gares/.opam/4.07.1/lib/ocaml)
 (S /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (S /home/gares/.opam/4.07.1/lib/re)
 (S /home/gares/.opam/4.07.1/lib/re/str)
 (S /home/gares/.opam/4.07.1/lib/result)
 (S /home/gares/.opam/4.07.1/lib/seq)
 (S /home/gares/LPCIC/elpi/src)
 (S /home/gares/LPCIC/elpi/trace/runtime)
 (FLG (-open Elpi__ -linkall)))
Runtime_trace_off
((EXCLUDE_QUERY_DIR)
 (B /home/gares/.opam/4.07.1/lib/camlp5)
 (B /home/gares/.opam/4.07.1/lib/ocaml)
 (B /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (B /home/gares/.opam/4.07.1/lib/re)
 (B /home/gares/.opam/4.07.1/lib/re/str)
 (B /home/gares/.opam/4.07.1/lib/result)
 (B /home/gares/.opam/4.07.1/lib/seq)
 (B /home/gares/LPCIC/elpi/_build/default/src/.elpi.objs/byte)
 (B
  /home/gares/LPCIC/elpi/_build/default/trace/runtime/.trace_ppx_runtime.objs/byte)
 (S /home/gares/.opam/4.07.1/lib/camlp5)
 (S /home/gares/.opam/4.07.1/lib/ocaml)
 (S /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (S /home/gares/.opam/4.07.1/lib/re)
 (S /home/gares/.opam/4.07.1/lib/re/str)
 (S /home/gares/.opam/4.07.1/lib/result)
 (S /home/gares/.opam/4.07.1/lib/seq)
 (S /home/gares/LPCIC/elpi/src)
 (S /home/gares/LPCIC/elpi/trace/runtime)
 (FLG (-open Elpi__ -linkall)))
Ptmap
((EXCLUDE_QUERY_DIR)
 (B /home/gares/.opam/4.07.1/lib/camlp5)
 (B /home/gares/.opam/4.07.1/lib/ocaml)
 (B /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (B /home/gares/.opam/4.07.1/lib/re)
 (B /home/gares/.opam/4.07.1/lib/re/str)
 (B /home/gares/.opam/4.07.1/lib/result)
 (B /home/gares/.opam/4.07.1/lib/seq)
 (B /home/gares/LPCIC/elpi/_build/default/src/.elpi.objs/byte)
 (B
  /home/gares/LPCIC/elpi/_build/default/trace/runtime/.trace_ppx_runtime.objs/byte)
 (S /home/gares/.opam/4.07.1/lib/camlp5)
 (S /home/gares/.opam/4.07.1/lib/ocaml)
 (S /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (S /home/gares/.opam/4.07.1/lib/re)
 (S /home/gares/.opam/4.07.1/lib/re/str)
 (S /home/gares/.opam/4.07.1/lib/result)
 (S /home/gares/.opam/4.07.1/lib/seq)
 (S /home/gares/LPCIC/elpi/src)
 (S /home/gares/LPCIC/elpi/trace/runtime)
 (FLG (-open Elpi__ -linkall)))
Ppx_deriving_runtime_proxy
((EXCLUDE_QUERY_DIR)
 (B /home/gares/.opam/4.07.1/lib/camlp5)
 (B /home/gares/.opam/4.07.1/lib/ocaml)
 (B /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (B /home/gares/.opam/4.07.1/lib/re)
 (B /home/gares/.opam/4.07.1/lib/re/str)
 (B /home/gares/.opam/4.07.1/lib/result)
 (B /home/gares/.opam/4.07.1/lib/seq)
 (B /home/gares/LPCIC/elpi/_build/default/src/.elpi.objs/byte)
 (B
  /home/gares/LPCIC/elpi/_build/default/trace/runtime/.trace_ppx_runtime.objs/byte)
 (S /home/gares/.opam/4.07.1/lib/camlp5)
 (S /home/gares/.opam/4.07.1/lib/ocaml)
 (S /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (S /home/gares/.opam/4.07.1/lib/re)
 (S /home/gares/.opam/4.07.1/lib/re/str)
 (S /home/gares/.opam/4.07.1/lib/result)
 (S /home/gares/.opam/4.07.1/lib/seq)
 (S /home/gares/LPCIC/elpi/src)
 (S /home/gares/LPCIC/elpi/trace/runtime)
 (FLG (-open Elpi__ -linkall)))
Parser
((EXCLUDE_QUERY_DIR)
 (B /home/gares/.opam/4.07.1/lib/camlp5)
 (B /home/gares/.opam/4.07.1/lib/ocaml)
 (B /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (B /home/gares/.opam/4.07.1/lib/re)
 (B /home/gares/.opam/4.07.1/lib/re/str)
 (B /home/gares/.opam/4.07.1/lib/result)
 (B /home/gares/.opam/4.07.1/lib/seq)
 (B /home/gares/LPCIC/elpi/_build/default/src/.elpi.objs/byte)
 (B
  /home/gares/LPCIC/elpi/_build/default/trace/runtime/.trace_ppx_runtime.objs/byte)
 (S /home/gares/.opam/4.07.1/lib/camlp5)
 (S /home/gares/.opam/4.07.1/lib/ocaml)
 (S /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (S /home/gares/.opam/4.07.1/lib/re)
 (S /home/gares/.opam/4.07.1/lib/re/str)
 (S /home/gares/.opam/4.07.1/lib/result)
 (S /home/gares/.opam/4.07.1/lib/seq)
 (S /home/gares/LPCIC/elpi/src)
 (S /home/gares/LPCIC/elpi/trace/runtime)
 (FLG
  (-pp
   "/home/gares/.opam/4.07.1/bin/camlp5o
   -I
   .
   -I
   +camlp5
   pa_extend.cmo
   pa_lexer.cmo"))
 (FLG (-open Elpi__ -linkall)))
Elpi
((EXCLUDE_QUERY_DIR)
 (B /home/gares/.opam/4.07.1/lib/camlp5)
 (B /home/gares/.opam/4.07.1/lib/ocaml)
 (B /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (B /home/gares/.opam/4.07.1/lib/re)
 (B /home/gares/.opam/4.07.1/lib/re/str)
 (B /home/gares/.opam/4.07.1/lib/result)
 (B /home/gares/.opam/4.07.1/lib/seq)
 (B /home/gares/LPCIC/elpi/_build/default/src/.elpi.objs/byte)
 (B
  /home/gares/LPCIC/elpi/_build/default/trace/runtime/.trace_ppx_runtime.objs/byte)
 (S /home/gares/.opam/4.07.1/lib/camlp5)
 (S /home/gares/.opam/4.07.1/lib/ocaml)
 (S /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (S /home/gares/.opam/4.07.1/lib/re)
 (S /home/gares/.opam/4.07.1/lib/re/str)
 (S /home/gares/.opam/4.07.1/lib/result)
 (S /home/gares/.opam/4.07.1/lib/seq)
 (S /home/gares/LPCIC/elpi/src)
 (S /home/gares/LPCIC/elpi/trace/runtime)
 (FLG (-open Elpi__ -linkall)))
Data
((EXCLUDE_QUERY_DIR)
 (B /home/gares/.opam/4.07.1/lib/camlp5)
 (B /home/gares/.opam/4.07.1/lib/ocaml)
 (B /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (B /home/gares/.opam/4.07.1/lib/re)
 (B /home/gares/.opam/4.07.1/lib/re/str)
 (B /home/gares/.opam/4.07.1/lib/result)
 (B /home/gares/.opam/4.07.1/lib/seq)
 (B /home/gares/LPCIC/elpi/_build/default/src/.elpi.objs/byte)
 (B
  /home/gares/LPCIC/elpi/_build/default/trace/runtime/.trace_ppx_runtime.objs/byte)
 (S /home/gares/.opam/4.07.1/lib/camlp5)
 (S /home/gares/.opam/4.07.1/lib/ocaml)
 (S /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (S /home/gares/.opam/4.07.1/lib/re)
 (S /home/gares/.opam/4.07.1/lib/re/str)
 (S /home/gares/.opam/4.07.1/lib/result)
 (S /home/gares/.opam/4.07.1/lib/seq)
 (S /home/gares/LPCIC/elpi/src)
 (S /home/gares/LPCIC/elpi/trace/runtime)
 (FLG (-open Elpi__ -linkall)))
Compiler
((EXCLUDE_QUERY_DIR)
 (B /home/gares/.opam/4.07.1/lib/camlp5)
 (B /home/gares/.opam/4.07.1/lib/ocaml)
 (B /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (B /home/gares/.opam/4.07.1/lib/re)
 (B /home/gares/.opam/4.07.1/lib/re/str)
 (B /home/gares/.opam/4.07.1/lib/result)
 (B /home/gares/.opam/4.07.1/lib/seq)
 (B /home/gares/LPCIC/elpi/_build/default/src/.elpi.objs/byte)
 (B
  /home/gares/LPCIC/elpi/_build/default/trace/runtime/.trace_ppx_runtime.objs/byte)
 (S /home/gares/.opam/4.07.1/lib/camlp5)
 (S /home/gares/.opam/4.07.1/lib/ocaml)
 (S /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (S /home/gares/.opam/4.07.1/lib/re)
 (S /home/gares/.opam/4.07.1/lib/re/str)
 (S /home/gares/.opam/4.07.1/lib/result)
 (S /home/gares/.opam/4.07.1/lib/seq)
 (S /home/gares/LPCIC/elpi/src)
 (S /home/gares/LPCIC/elpi/trace/runtime)
 (FLG (-open Elpi__ -linkall)))
Builtin_stdlib
((EXCLUDE_QUERY_DIR)
 (B /home/gares/.opam/4.07.1/lib/camlp5)
 (B /home/gares/.opam/4.07.1/lib/ocaml)
 (B /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (B /home/gares/.opam/4.07.1/lib/re)
 (B /home/gares/.opam/4.07.1/lib/re/str)
 (B /home/gares/.opam/4.07.1/lib/result)
 (B /home/gares/.opam/4.07.1/lib/seq)
 (B /home/gares/LPCIC/elpi/_build/default/src/.elpi.objs/byte)
 (B
  /home/gares/LPCIC/elpi/_build/default/trace/runtime/.trace_ppx_runtime.objs/byte)
 (S /home/gares/.opam/4.07.1/lib/camlp5)
 (S /home/gares/.opam/4.07.1/lib/ocaml)
 (S /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (S /home/gares/.opam/4.07.1/lib/re)
 (S /home/gares/.opam/4.07.1/lib/re/str)
 (S /home/gares/.opam/4.07.1/lib/result)
 (S /home/gares/.opam/4.07.1/lib/seq)
 (S /home/gares/LPCIC/elpi/src)
 (S /home/gares/LPCIC/elpi/trace/runtime)
 (FLG (-open Elpi__ -linkall)))
Builtin_set
((EXCLUDE_QUERY_DIR)
 (B /home/gares/.opam/4.07.1/lib/camlp5)
 (B /home/gares/.opam/4.07.1/lib/ocaml)
 (B /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (B /home/gares/.opam/4.07.1/lib/re)
 (B /home/gares/.opam/4.07.1/lib/re/str)
 (B /home/gares/.opam/4.07.1/lib/result)
 (B /home/gares/.opam/4.07.1/lib/seq)
 (B /home/gares/LPCIC/elpi/_build/default/src/.elpi.objs/byte)
 (B
  /home/gares/LPCIC/elpi/_build/default/trace/runtime/.trace_ppx_runtime.objs/byte)
 (S /home/gares/.opam/4.07.1/lib/camlp5)
 (S /home/gares/.opam/4.07.1/lib/ocaml)
 (S /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (S /home/gares/.opam/4.07.1/lib/re)
 (S /home/gares/.opam/4.07.1/lib/re/str)
 (S /home/gares/.opam/4.07.1/lib/result)
 (S /home/gares/.opam/4.07.1/lib/seq)
 (S /home/gares/LPCIC/elpi/src)
 (S /home/gares/LPCIC/elpi/trace/runtime)
 (FLG (-open Elpi__ -linkall)))
Builtin_map
((EXCLUDE_QUERY_DIR)
 (B /home/gares/.opam/4.07.1/lib/camlp5)
 (B /home/gares/.opam/4.07.1/lib/ocaml)
 (B /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (B /home/gares/.opam/4.07.1/lib/re)
 (B /home/gares/.opam/4.07.1/lib/re/str)
 (B /home/gares/.opam/4.07.1/lib/result)
 (B /home/gares/.opam/4.07.1/lib/seq)
 (B /home/gares/LPCIC/elpi/_build/default/src/.elpi.objs/byte)
 (B
  /home/gares/LPCIC/elpi/_build/default/trace/runtime/.trace_ppx_runtime.objs/byte)
 (S /home/gares/.opam/4.07.1/lib/camlp5)
 (S /home/gares/.opam/4.07.1/lib/ocaml)
 (S /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (S /home/gares/.opam/4.07.1/lib/re)
 (S /home/gares/.opam/4.07.1/lib/re/str)
 (S /home/gares/.opam/4.07.1/lib/result)
 (S /home/gares/.opam/4.07.1/lib/seq)
 (S /home/gares/LPCIC/elpi/src)
 (S /home/gares/LPCIC/elpi/trace/runtime)
 (FLG (-open Elpi__ -linkall)))
Builtin_checker
((EXCLUDE_QUERY_DIR)
 (B /home/gares/.opam/4.07.1/lib/camlp5)
 (B /home/gares/.opam/4.07.1/lib/ocaml)
 (B /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (B /home/gares/.opam/4.07.1/lib/re)
 (B /home/gares/.opam/4.07.1/lib/re/str)
 (B /home/gares/.opam/4.07.1/lib/result)
 (B /home/gares/.opam/4.07.1/lib/seq)
 (B /home/gares/LPCIC/elpi/_build/default/src/.elpi.objs/byte)
 (B
  /home/gares/LPCIC/elpi/_build/default/trace/runtime/.trace_ppx_runtime.objs/byte)
 (S /home/gares/.opam/4.07.1/lib/camlp5)
 (S /home/gares/.opam/4.07.1/lib/ocaml)
 (S /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (S /home/gares/.opam/4.07.1/lib/re)
 (S /home/gares/.opam/4.07.1/lib/re/str)
 (S /home/gares/.opam/4.07.1/lib/result)
 (S /home/gares/.opam/4.07.1/lib/seq)
 (S /home/gares/LPCIC/elpi/src)
 (S /home/gares/LPCIC/elpi/trace/runtime)
 (FLG (-open Elpi__ -linkall)))
Builtin
((EXCLUDE_QUERY_DIR)
 (B /home/gares/.opam/4.07.1/lib/camlp5)
 (B /home/gares/.opam/4.07.1/lib/ocaml)
 (B /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (B /home/gares/.opam/4.07.1/lib/re)
 (B /home/gares/.opam/4.07.1/lib/re/str)
 (B /home/gares/.opam/4.07.1/lib/result)
 (B /home/gares/.opam/4.07.1/lib/seq)
 (B /home/gares/LPCIC/elpi/_build/default/src/.elpi.objs/byte)
 (B
  /home/gares/LPCIC/elpi/_build/default/trace/runtime/.trace_ppx_runtime.objs/byte)
 (S /home/gares/.opam/4.07.1/lib/camlp5)
 (S /home/gares/.opam/4.07.1/lib/ocaml)
 (S /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (S /home/gares/.opam/4.07.1/lib/re)
 (S /home/gares/.opam/4.07.1/lib/re/str)
 (S /home/gares/.opam/4.07.1/lib/result)
 (S /home/gares/.opam/4.07.1/lib/seq)
 (S /home/gares/LPCIC/elpi/src)
 (S /home/gares/LPCIC/elpi/trace/runtime)
 (FLG (-open Elpi__ -linkall)))
Ast
((EXCLUDE_QUERY_DIR)
 (B /home/gares/.opam/4.07.1/lib/camlp5)
 (B /home/gares/.opam/4.07.1/lib/ocaml)
 (B /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (B /home/gares/.opam/4.07.1/lib/re)
 (B /home/gares/.opam/4.07.1/lib/re/str)
 (B /home/gares/.opam/4.07.1/lib/result)
 (B /home/gares/.opam/4.07.1/lib/seq)
 (B /home/gares/LPCIC/elpi/_build/default/src/.elpi.objs/byte)
 (B
  /home/gares/LPCIC/elpi/_build/default/trace/runtime/.trace_ppx_runtime.objs/byte)
 (S /home/gares/.opam/4.07.1/lib/camlp5)
 (S /home/gares/.opam/4.07.1/lib/ocaml)
 (S /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (S /home/gares/.opam/4.07.1/lib/re)
 (S /home/gares/.opam/4.07.1/lib/re/str)
 (S /home/gares/.opam/4.07.1/lib/result)
 (S /home/gares/.opam/4.07.1/lib/seq)
 (S /home/gares/LPCIC/elpi/src)
 (S /home/gares/LPCIC/elpi/trace/runtime)
 (FLG (-open Elpi__ -linkall)))
API
((EXCLUDE_QUERY_DIR)
 (B /home/gares/.opam/4.07.1/lib/camlp5)
 (B /home/gares/.opam/4.07.1/lib/ocaml)
 (B /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (B /home/gares/.opam/4.07.1/lib/re)
 (B /home/gares/.opam/4.07.1/lib/re/str)
 (B /home/gares/.opam/4.07.1/lib/result)
 (B /home/gares/.opam/4.07.1/lib/seq)
 (B /home/gares/LPCIC/elpi/_build/default/src/.elpi.objs/byte)
 (B
  /home/gares/LPCIC/elpi/_build/default/trace/runtime/.trace_ppx_runtime.objs/byte)
 (S /home/gares/.opam/4.07.1/lib/camlp5)
 (S /home/gares/.opam/4.07.1/lib/ocaml)
 (S /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (S /home/gares/.opam/4.07.1/lib/re)
 (S /home/gares/.opam/4.07.1/lib/re/str)
 (S /home/gares/.opam/4.07.1/lib/result)
 (S /home/gares/.opam/4.07.1/lib/seq)
 (S /home/gares/LPCIC/elpi/src)
 (S /home/gares/LPCIC/elpi/trace/runtime)
 (FLG (-open Elpi__ -linkall)))
Elpi__
((EXCLUDE_QUERY_DIR)
 (B /home/gares/.opam/4.07.1/lib/camlp5)
 (B /home/gares/.opam/4.07.1/lib/ocaml)
 (B /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (B /home/gares/.opam/4.07.1/lib/re)
 (B /home/gares/.opam/4.07.1/lib/re/str)
 (B /home/gares/.opam/4.07.1/lib/result)
 (B /home/gares/.opam/4.07.1/lib/seq)
 (B /home/gares/LPCIC/elpi/_build/default/src/.elpi.objs/byte)
 (B
  /home/gares/LPCIC/elpi/_build/default/trace/runtime/.trace_ppx_runtime.objs/byte)
 (S /home/gares/.opam/4.07.1/lib/camlp5)
 (S /home/gares/.opam/4.07.1/lib/ocaml)
 (S /home/gares/.opam/4.07.1/lib/ppx_deriving/runtime)
 (S /home/gares/.opam/4.07.1/lib/re)
 (S /home/gares/.opam/4.07.1/lib/re/str)
 (S /home/gares/.opam/4.07.1/lib/result)
 (S /home/gares/.opam/4.07.1/lib/seq)
 (S /home/gares/LPCIC/elpi/src)
 (S /home/gares/LPCIC/elpi/trace/runtime)
 (FLG (-open Elpi__ -linkall)))
```

**Comment by voodoos** [comment] 2021-01-27 13:38
@gares That makes little sense but it looks like putting the `%{input-file}` at the end of the command line make the flag appear in the Merlin configuration:

```ocaml
(preprocess (per_module
    ((action (run %{project_root}/ppxfindcache/ppxfindcache2.exe
                    --cache-file %{dep:.ppcache/API.ml}
                    --cache-file %{dep:.ppcache/API.mli}
                    --cache-file %{dep:.ppcache/util.ml}
                    --cache-file %{dep:.ppcache/util.mli}
                    --cache-file %{dep:.ppcache/ast.ml}
                    --cache-file %{dep:.ppcache/ast.mli}
                    --cache-file %{dep:.ppcache/data.ml}
                    --cache-file %{dep:.ppcache/compiler.ml}
                    --cache-file %{dep:.ppcache/compiler.mli}
                    %{input-file}))
              API ast data compiler)
    ((action (run %{project_root}/ppxfindcache/ppxfindcache.exe
                    --ppx-opt --cookie
                    --ppx-opt "elpi_trace=\"true\""
                    --cache-file %{dep:.ppcache/runtime_trace_on.ml}
                    --cache-file %{dep:.ppcache/runtime_trace_on.mli}
                    %{input-file}))
              runtime_trace_on)
    ((action (run %{project_root}/ppxfindcache/ppxfindcache.exe
                    --ppx-opt --cookie
                    --ppx-opt "elpi_trace=\"false\""
                    --cache-file %{dep:.ppcache/runtime_trace_off.ml}
                    --cache-file %{dep:.ppcache/runtime_trace_off.mli}
                     %{input-file}))
              runtime_trace_off)
    ((action (run camlp5o -I . -I +camlp5 pa_extend.cmo pa_lexer.cmo %{input-file})) parser)
    ))
```

Can you try it and check that this indeed solve the issue ?

@rgrinberg do you have an idea why the order of the parameters could be of significance here ?

**Comment by gares** [comment] 2021-01-27 14:03
Thanks @voodoos ! I would have never guessed this work around. Now I get my [%extensions] processed.

There is still a glitch, if you open src/runtime_trace_on.ml (or _off.ml) you get an error on the first line (which is a comment):
"This expression has type int but an expression was expected of type bool ocamllsp"

Is this related to the ppx handling?

**Comment by gares** [comment] 2021-01-27 14:14
Actually I get errors like `Unbound Constructor Caml1999M023` so I guess "merlin" expects some text and not a marshaled AST?

**Comment by voodoos** [comment] 2021-01-27 14:17
> Actually I get errors like `Unbound Constructor Caml1999M023` so I guess "merlin" expects some text and not a marshaled AST?

I need to summon other magicians to answer that: @trefis, @let-def ?

**Comment by gares** [comment] 2021-01-27 17:48
OK, I understood a bit more: all `run` are commands that generate marshaled AST, but merlin gets a `-pp` option (and not a `-ppx`).

I don't know if `run` is expected to return sources, or is allowed to return both source and AST, but you assume source (hence you pick `-pp` for merlin). I guess you generate `-ppx` for `pps` directives.

Is there a way I can ask for a `-ppx` directive in the merlin conf file even if the ppx is run via `run` and not `pps`?

**Comment by gares** [comment] 2021-01-27 17:51
FTR `ppxfindcache.exe` is a thing of mine which does call a standard pps behind the scenes but also does other things like also saving the source of the generated AST on the side. I don't think I can turn it into a regular pps without major hacks.

**Comment by rgrinberg** [comment] 2021-01-28 02:19
> do you have an idea why the order of the parameters could be of significance here ?

Because the way we handle `action` preprocessors are a hack. There's no way to pass a general action to merlin, so we do a best effort of converting an action to something that can be passed to merlin.

**Comment by voodoos** [comment] 2021-01-28 09:52
So to sum-up:

1. The ordering issue is due to the "best effort of converting an action to something that can be passed to merlin". We should at least mention it in the documentation, but a real improvement would be to have a better way to pass actions to Merlin.
2. You have a PPS in disguise that you run with `run` and apparently Dune wrongly assumes it is outputting text (by opposition to marshaled AST). I feel like you should open a new issue about this.

Modulo 1, it seems that per-module configuration is working as expected, and we should close this issue and move the discussion elsewhere.

**Closed by voodoos** 2021-01-28 09:52 UTC
