### ISSUE TITLE
dune~dev fails to build base due to missing dune.configurator

### ISSUE THREAD

**Issue by avsm** [ocaml/dune#2679] opened 2019-09-29 08:20 UTC
Trying to build base with dune~dev currently fails with:

```
#=== ERROR while compiling base.v0.12.2 =======================================#
# context     2.0.4 | linux/x86_64 | ocaml-base-compiler.4.08.0 | git+file:///home/opam/opam-repository
# path        ~/.opam/4.08/.opam-switch/build/base.v0.12.2
# command     ~/.opam/4.08/bin/dune build -p base -j 71
# exit-code   1
# env-file    ~/.opam/log/base-7113-a19e5c.env
# output-file ~/.opam/log/base-7113-a19e5c.out
### output ###
# File "src/discover/dune", line 1, characters 41-58:
# 1 | (executables (names discover) (libraries dune.configurator)
#                                              ^^^^^^^^^^^^^^^^^
# Error: Library "dune.configurator" not found.
# Hint: try: dune external-lib-deps --missing -p base -j 71 @install
```

This is because dune-configurator is now a separate library, and must be installed.  However, this scheme is incompatible with having a vendored version of base that builds with both dune 1.11 _and_ 2.0~dev, since the `dune-configurator` library and its dependencies are selected using the opam solver (via `dune` version constraints).

Is the expectation that vendoring the dune 2.0 private-libs will build with dune 1.11.3? If so, it's then possible to vendor the dune.git versions of the libraries as pin for now, and the duniverse repository will build with both versions.

Otherwise we'll have to restrict the duniverse tool results to either dune 1.x or 2.x, which is not the end of the world but an unfortunate restriction.

**Comment by diml** [comment] 2019-09-30 07:25
Do you have both dune sources and base sources in the same workspace? If this is the case, then the following combinations should work:

- dune 1.x sources with dune 1.x or dune 2.x binary
- dune 2.x sources with dune 2.x binary

**Comment by diml** [comment] 2019-09-30 07:27
Oh, or is that we updated the dependencies to be `dune < 2.x || (dune >= 2.x && dune-configurator)`, however this was only dune in the opam-repository and not upstreamed in the various upstream repositories?

**Comment by dinosaure** [comment] 2019-10-09 11:24
Currently, this bug still is reproducible with `~dev` and a fresh OPAM switch:

```sh
$ opam switch create dune 4.08.1
$ opam pin add dune --dev
$ opam install lwt
File "src/unix/config/dune", line 8, character 12-29:
8 |  (libraries dune.configurator))
...
```

`base` should be a better example when `lwt` is huge.

**Comment by diml** [comment] 2019-10-09 12:16
That's intentional. We want to make the `dune` package be a pure binary, so we moved `dune.configurator` into a separate `dune-configurator` package. The name `dune.configurator` is still available for backward compatibility though. The dependency on `dune-configurator` was added to all packages that use `dune.configurator` in opam, so you should just have to pin `dune-configurator`

**Comment by dinosaure** [comment] 2019-10-09 12:30
Hmmhmm, ok I believe my OPAM repository does not reflect your update. I will try to update it and I hope close the issue :+1:.

**Comment by diml** [comment] 2019-10-09 13:56
it might be because there is currently a dummy dune-configurator package in opam, so you get this one installed.

**Comment by rgrinberg** [comment] 2020-10-22 16:52
I think we fixed these issues going forward. Please re-open if there are still any problems.

**Closed by rgrinberg** 2020-10-22 16:52 UTC
