### ISSUE TITLE
The build process is stalling after out of memory

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/dune#1615] opened 2018-12-06 15:36 UTC
While building a whole bunch of packages in parallel, one of them stalled after hitting a space limit and stayed in this state until I killed the process manually (SIGINT):
```
+ /home/opam/.opam/4.03.0/bin/jbuilder "build" "-p" "ppx_bench" "-j" "71" (CWD=/home/opam/.opam/4.03.0/.opam-switch/build/ppx_bench.v0.9.1)
- Error: exception Sys_error("No space left on device")
- Backtrace:
- Raised at file "src/dep_path.ml", line 46, characters 32-55
- Called from file "src/fiber/fiber.ml", line 243, characters 6-18
- /-----------------------------------------------------------------------
- | Internal error: Fiber.Execution_context.forward_error: error handler raised.
- | Sys_error("No space left on device")
- | Called from file "src/report_error.ml", line 171, characters 6-24
- | Called from file "src/fiber/fiber.ml", line 243, characters 6-18
- | Called from file "src/fiber/fiber.ml", line 56, characters 6-20
- |
- | Original exception was: Sys_error("No space left on device")
- | Called from file "src/report_error.ml", line 171, characters 6-24
- | Called from file "src/fiber/fiber.ml", line 243, characters 6-18
- \-----------------------------------------------------------------------
- /-----------------------------------------------------------------------
- | Internal error: Fiber.Execution_context.forward_error: error handler raised.
- | Sys_error("No space left on device")
- | Called from file "format.ml", line 1247, characters 20-38
- | Called from file "src/fiber/fiber.ml", line 79, characters 4-23
- | Called from file "src/fiber/fiber.ml", line 56, characters 6-20
- |
- | Original exception was: Sys_error("No space left on device")
- | Raised at file "src/dep_path.ml", line 46, characters 32-55
- | Called from file "src/fiber/fiber.ml", line 243, characters 6-18
- \-----------------------------------------------------------------------
- /-----------------------------------------------------------------------
- | Internal error: Fiber.Execution_context.forward_error: error handler raised.
- | Sys_error("No space left on device")
- | Called from file "format.ml", line 1247, characters 20-38
- | Called from file "src/fiber/fiber.ml", line 79, characters 4-23
- | Called from file "src/fiber/fiber.ml", line 56, characters 6-20
- |
- | Original exception was: Sys_error("No space left on device")
- | Raised at file "src/dep_path.ml", line 46, characters 32-55
- | Called from file "src/fiber/fiber.ml", line 243, characters 6-18
- \-----------------------------------------------------------------------
- malloc_consolidate(): invalid chunk size
- malloc_consolidate(): invalid chunk size
-          ppx src/ppx_bench.pp.mli (got signal ABRT)
- (cd _build/default && .ppx/jbuild/687c80332aff00d0f3beedee2ab1fbbb/ppx.exe --cookie 'library-name="ppx_bench"' -o src/ppx_bench.pp.mli --intf src/ppx_bench.mli -diff-cmd - -dump-ast)
-          ppx src/ppx_bench.pp.ml (got signal ABRT)
- (cd _build/default && .ppx/jbuild/687c80332aff00d0f3beedee2ab1fbbb/ppx.exe --cookie 'library-name="ppx_bench"' -o src/ppx_bench.pp.ml --impl src/ppx_bench.ml -diff-cmd - -dump-ast)
```
dune version: 1.6.0

**Comment by kit-ty-kate** [comment] 2018-12-06 15:37
I'm not sure if that should be an issue in dune or ppx_bench though

**Comment by diml** [comment] 2018-12-10 06:51
That does look like an issue in Dune. The issue is that it happens at a place where we don't expect errors (we are trying to handle an exception from the catch-all error handler).

Looking at the code, it looks like it is printing to stderr that is causing the `No space left on device` error, however I don't understand how we can see this error if stderr is full.

**Comment by diml** [comment] 2018-12-15 17:18
I reworked a bit this part of Dune in #1672, so this issue should disappear once #1672 is merged.

**Comment by diml** [comment] 2018-12-15 23:46
I believe this is fixed in master

**Closed by diml** 2018-12-15 23:46 UTC
