### ISSUE TITLE
dune build --watch: Unix.Unix_error(Unix.EINVAL, "bind", "") on Dune 3.x.x on WSL

### ISSUE THREAD

**Issue by aantron** [ocaml/dune#7541] opened 2023-04-13 06:55 UTC
## Expected Behavior

```
$ dune build --watch
Success, waiting for filesystem changes...
```

## Actual Behavior

Immediately after `dune build --watch`:

```
Uncaught RPC Error
Unix.Unix_error(Unix.EINVAL, "bind", "")
backtrace:
Raised by primitive operation at Csexp_rpc.Socket.U.bind in file
"src/csexp_rpc/csexp_rpc.ml", line 61, characters 23-40
Called from Csexp_rpc.Socket.bind in file "src/csexp_rpc/csexp_rpc.ml"
(inlined), line 114, characters 13-51
Called from Csexp_rpc.Server.create in file "src/csexp_rpc/csexp_rpc.ml",
line 308, characters 10-33
Called from Dune_rpc_impl__server.create in file
"src/dune_rpc_impl/server.ml", line 411, characters 13-72
Called from CamlinternalLazy.force_lazy_block in file "camlinternalLazy.ml",
line 31, characters 17-27
Re-raised at CamlinternalLazy.force_lazy_block in file "camlinternalLazy.ml",
line 36, characters 4-11
Called from Dune_rpc_impl__server.Run.run.run in file
"src/dune_rpc_impl/server.ml", line 72, characters 19-38
Called from Fiber__scheduler.exec in file "otherlibs/fiber/src/scheduler.ml",
line 73, characters 8-11
```

and no builds are started immediately or upon saving files in the project.

This occurs with all Dune 3.x versions I tested: 3.7.0, 3.4.0, 3.2.0, 3.0.2. The 3.0.2 output was:

```
Done: 0% (0/0, 0 left) (jobs: 0)/-----------------------------------------------------------------------
| Internal error: Uncaught exception.
| Unix.Unix_error(Unix.EINVAL, "bind", "")
| Raised by primitive operation at Csexp_rpc.Socket.U.bind in file "src/csexp_rpc/csexp_rpc.ml", line 30, characters 23-40
| Called from Csexp_rpc.Socket.bind in file "src/csexp_rpc/csexp_rpc.ml" (inlined), line 83, characters 13-51
| Called from Csexp_rpc.Server.Transport.create in file "src/csexp_rpc/csexp_rpc.ml", line 237, characters 6-29
| Called from Stdune__exn_with_backtrace.try_with in file "otherlibs/stdune/exn_with_backtrace.ml", line 9, characters 8-12
| Re-raised at Stdune__exn.raise_with_backtrace in file "otherlibs/stdune/exn.ml" (inlined), line 36, characters 27-56
| Called from Stdune__exn_with_backtrace.reraise in file "otherlibs/stdune/exn_with_backtrace.ml", line 18, characters 33-71
| Called from Fiber.O.(>>|).(fun) in file "src/fiber/fiber.ml", line 250, characters 36-41
| Called from Fiber.Scheduler.exec in file "src/fiber/fiber.ml", line 854, characters 10-13
\-----------------------------------------------------------------------

Error:
inotify_add_watch(/mnt/c/Program Files/WindowsApps/Microsoft.WindowsTerminalPreview_1.17.10234.0_x64__8wekyb3d8bbwe): Bad file descriptor
```

`dune build --watch` works on Dune 2.9.3.

## Reproduction

`foo.ml`:

```ocaml
let () =
  print_endline "foo"
```

`dune`:

```
(executable
 (name foo))
```

```
$ dune build --watch
```

## Specifications

- Version of `dune` (output of `dune --version`): 3.7.0
- Version of `ocaml` (output of `ocamlc --version`): 4.14.1
- Operating system (distribution and version): WSL1, Ubuntu 20.04.1 LTS

**Comment by Alizter** [comment] 2023-04-13 09:19
cc @nojb

**Comment by aantron** [comment] 2023-04-13 14:18
Thanks! I am deliberately using WSL as an almost-Linux to develop on "Linux." My current workaround is to use Dune 2.9.3 where I can get away with it :)

**Comment by nojb** [comment] 2023-04-13 14:24
I cannot reproduce with 3.7.1. Which version of WSL are you using? (`wsl.exe --version`)
```
nojebar@PERVERSESHEAF:~/t/foo$ wsl.exe --version
Version WSL : 1.2.0.0
Version du noyau : 5.15.90.1
Version WSLg : 1.0.51
Version MSRDC : 1.2.3770
Version direct3D : 1.608.2-61064218
Version de DXCore : 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Version de Windows : 10.0.22621.1555
```

**Comment by aantron** [comment] 2023-04-13 17:18
@nojb, were you running WSL1 or WSL2?

**Comment by nojb** [comment] 2023-04-13 18:08
> @nojb, were you running WSL1 or WSL2?

WSL2. Do I understand that you still hit the problem after upgrading? I am not able to reproduce...

**Comment by nojb** [comment] 2023-04-13 18:39
Shot in the dark: use `strace dune build --watch` to try to glean some more information about the system call that fails?

**Comment by aantron** [comment] 2023-04-14 01:05
I am deliberately using WSL1. As you probably know, WSL1 and WSL2 are very different from each other, so I suspect you would have to try this in WSL1 to reproduce it.

**Comment by aantron** [comment] 2023-04-14 09:08
As of a year or so ago, WSL1 had much better integration between the "Linux" and Windows file systems.

**Comment by nojb** [comment] 2023-04-14 09:17
> As of a year or so ago, WSL1 had much better integration between the "Linux" and Windows file systems.

Do you remember what exactly worked better in WSL1?

I don't remember the details regarding WSL1, but WSL2 works just fine with native Windows: you can access the native Windows file system from within WSL2 at `/mnt/c` and conversely, you can access the WSL2 file system from within Windows under the `\\wsl$` prefix. Performance is not bad and it works pretty flawlessly in my experience.

Coming back to this report, I'm not sure it will be easy to fix given WSL1's imperfect emulation of the Linux system call layer. I would suggest that you give WSL2 a try and see if you run into any issues. (Also, WSL1 is officially legacy and will not receive any further improvements from MS.)

**Comment by aantron** [comment] 2023-04-14 09:27
As I recall, accessing NTFS from WSL2 was extremely slow, far too slow for the large builds and opam installs I often do while developing. I don't have time in the immediate term to try WSL2 again and see if this has changed.

All software I use works fine on WSL1, including OCaml software. Dune 3 is the exception at the moment.

**Comment by nojb** [comment] 2023-04-14 10:00
> As I recall, accessing NTFS from WSL2 was extremely slow, far too slow for the large builds and opam installs I often do while developing.

Indeed, there's a considerable performance penalty to using NTFS from within WSL2 due to the network layer. But the solution is to store most things directly in the WSL2 filesystem, it is much faster (close to native Linux performance). See eg https://vxlabs.com/2019/12/06/wsl2-io-measurements.

> All software I use works fine on WSL1, including OCaml software. Dune 3 is the exception at the moment.

Someone using WSL1 will need to investigate. I can give it a try, but it will have to wait until I get some free time to install WSL1.

**Comment by Alizter** [comment] 2023-04-14 10:39
FTR, WSL1 emulates unix system calls by using corresponding windows ones, and this mapping is not perfect hence why the syscalls didn't work in this situation. We could introduce special C stubs that would be invoked on WSL1 and patch the Unix library. I wonder if anybody ran into this issue working with OCaml on WSL1. Doing a bind is not an uncommon operation.

Another observation, the file system in WSL1 that we are trying to bind to in Dune might be the wrong one. If we switch to using the correct one then perhaps the syscall will work.

**Comment by nojb** [comment] 2023-04-14 12:29
> > All software I use works fine on WSL1, including OCaml software. Dune 3 is the exception at the moment.
> 
> Someone using WSL1 will need to investigate. I can give it a try, but it will have to wait until I get some free time to install WSL1.

I was actually able to test this quickly (one can switch the version of WSL used for an existing distribution using `wsl.exe --set-version <Distribution> <Version>`). Unfortunately, I cannot reproduce: `dune build --watch` does not crash.

**Comment by aantron** [comment] 2023-04-19 06:37
I've almost completed a switch to WSL2, so this issue will not be needed for me soon. Thank you.

**Comment by nojb** [comment] 2023-04-19 06:53
> I've almost completed a switch to WSL2, so this issue will not be needed for me soon. Thank you.

Thanks for letting us know. As I could not reproduce using WSL1 in my machine, I suggest we close this issue for now.

**Closed by nojb** 2023-04-19 06:53 UTC
Labels: bug, windows, wsl
