### ISSUE TITLE
(inline_tests) + ppx_expect requires the ppx_expect.evaluator

### ISSUE THREAD

**Issue by zindel** [ocaml/dune#794] opened 2018-05-23 08:33 UTC
Hi! Thank you adding the testing support! It simplified my custom configuration and the testing workflow a lot.

There is one minor hiccup I noticed when following the instructions in this [chapter](http://jbuilder.readthedocs.io/en/latest/tests.html#inline-expectation-tests). The tests were executed (I had a bug in the test code initially, so got the traceback), but diffs were not shown.

I was able to fix it by adding the `ppx_expect.evaluator` to the `(libraries)` list. Maybe, documentation has to be updated to reflect it (and I am happy to make the PR), is it a bug, or am I missing something obvious here?

My environment is:
- jbuilder 1.0.0+beta20
- ppx_expect v0.11.0

**Comment by diml** [comment] 2018-05-23 09:55
Could you try reinstalling ppx_expect? It should fix the issue

**Comment by zindel** [comment] 2018-05-23 11:15
@diml It does. Thank you! Is there something to learn/remember? Like "ppx_expect should be installed after the jbuilder" or similar. Trying to understand, what was wrong this time...

**Comment by diml** [comment] 2018-06-02 09:20
Closing this since I believe the issue is sorted

**Closed by diml** 2018-06-02 09:20 UTC

**Comment by seantalts** [comment] 2019-02-17 15:30
hey! I'm running into the same issue... is the recommended course of action to install ppx_expect after dune? or just to always re-install ppx_expect? I actually can't get it to work now on Linux - not showing diffs and doesn't create anything for promotion. Not sure if this is the same issue.

**Comment by diml** [comment] 2019-02-18 13:17
Hey @seantalts! It's the support for jbuilder that is getting a little rusty. This should be fixed by #1853.

**Comment by seantalts** [comment] 2019-02-18 14:02
Ah, thanks! Do you think it would work for us to switch to a previous version of ppx_expect for now?

**Comment by diml** [comment] 2019-02-18 14:27
I don't think that would be enough. You have several choices:

- use dune < 1.7.0
- use dune master
- use the development versions of ppx_inline_test and co, which have switched to dune: `opam repository add janestreet-dev https://github.com/janestreet/opam-repository` (this might be more work though, due to potential breaking changes in other libraries)

or just wait for dune 1.7.2. We'll do a minor release this week. It would be nice if you could confirm that it works with dune master though :). To be clear, to test with dune master, you would need to pin `dune` + re-install `ppxlib`, `ppx_inline_test` and `ppx_expect`. These are the three packages that are affected by the changes in master.

**Comment by seantalts** [comment] 2019-02-18 14:36
I will try it out with dune master later today or early tomorrow :) Is the opam command `opam pin add dune https://github.com/ocaml/dune.git#master`?

**Comment by diml** [comment] 2019-02-18 15:16
Yes, or simply: `opam pin add --dev dune`

**Comment by seantalts** [comment] 2019-02-18 18:09
Didn't seem to work ! Also had to reinstall core_kernel after using opam to remove and then install ppxlib ppx_inline_test ppx_expect. Maybe I didn't get the right dune? 
```
$ dune --version
1.7.1
```

**Comment by seantalts** [comment] 2019-02-18 18:48
I take it back! apparently even if you pin the package, you have to manually remove and install it. So now I see `1.7.1-16-gdbc8f708` and inline expect tests work. Thanks!

**Comment by diml** [comment] 2019-02-19 07:57
Great, thanks for testing! It does seem odd that you have to manually remove&reinstall the package after pinning it though.
