### ISSUE TITLE
Per module ocamlflags

### ISSUE THREAD

**Issue by Kakadu** [ocaml/dune#3551] opened 2020-06-14 16:31 UTC
Today dune can configure  _preprocess commands_ per module but I also want to configure _preprocess flags_ per module. My project has compile-time code generation from `mini ml` to `ocaml` (using compiler-libs) and I want to specify `-open` directives per module(i.e. generated file) and not per project. Current alternative is to put generated files into separate libraries and I don't really like this approach.

**Comment by jeremiedimino** [comment] 2020-06-23 08:54
Just to make sure I understand currently; an example of what you are trying to do is:

you have a library containing two modules `Foo` and `Bar` and you want to pass `-open X` when compiling `foo.{ml,mli}` but not when compiling `bar.{ml,mli}`. Is that correct?

**Comment by nojb** [comment] 2020-06-23 08:56
Per-module flags are also useful to pass, say, `-noassert` for a specific module for performance reasons.

**Comment by Kakadu** [comment] 2020-06-23 12:17
> you have a library containing two modules `Foo` and `Bar` and you want to pass `-open X` when compiling `foo.{ml,mli}` but not when compiling `bar.{ml,mli}`. Is that correct?
Yes, it's correct

**Comment by jeremiedimino** [comment] 2020-06-23 13:16
@nojb, agreed. It's actually a pretty old feature request: #61

I remember that someone looked at this a long time ago, and then @rgrinberg also looked at this a bit more recently, but we never ended up integrating this feature. IIRC, we never finalised the design. Might be worth re-opening this discussion.

**Comment by rgrinberg** [comment] 2020-06-26 05:05
Yes indeed. I'm closing this issue because it's a duplicate of #61 however.

**Closed by rgrinberg** 2020-06-26 05:05 UTC
