### ISSUE TITLE
Code compiles normally, but doesn't compile with --profile release

### ISSUE THREAD

**Issue by TypesLogicsCats** [ocaml/dune#2021] opened 2019-04-04 23:21 UTC
[dune-bug.tar.gz](https://github.com/ocaml/dune/files/3045794/dune-bug.tar.gz)

    dune build main.exe
    dune build main.exe --profile release

The former line causes the code to compile successfully. The latter line causes a compile error about an unbound type variable.

**Comment by emillon** [comment] 2019-04-08 12:04
Thanks for this bug report.

This can be reproduced out of dune with the following:

```
(* class.ml *)
class c = object
  (* unit -> 'a -> unit, 'a is unbound *)
  method m f =
    f ();
    ()
end
```

```
% ocamlc -c -strict-sequence class.ml
% ocamlc -c class.ml                 
File "class.ml", line 1, characters 0-94:
Error: Some type variables are unbound in this type:
         class c : object method m : (unit -> 'a) -> unit end
       The method m has type (unit -> 'a) -> unit where 'a is unbound
```

This is caused by dune setting `-strict-sequence` in the dev profile but not in the release profile.

I thought that `-strict-sequence` would reject strictly more programs than when it's not set, but this doesn't seem to be the case. I'm not sure whether that can be considered an ocaml bug. @diml might know?

In the meantime, workaround is to add `(flags :standard -strict-sequence)` to the dune file.

**Comment by TheAspiringHacker** [comment] 2019-04-09 00:09
I did not know before of the `-strict-sequence` flag, but looking at it, it makes the LHS of the sequence operator have type `unit`. So, instead of

    x : a, y : b
    ————————
    x; y : b

the typing rule is

    x : unit, y : b
    x; y : b

Therefore, in the code

    class c = object
      (* (unit -> 'a) -> unit, 'a is unbound *)
      method m f =
        f ();
        ()
    end

f has inferred type `unit -> 'a` without the flag and `unit -> unit` with it. Methods cannot be polymorphic, so the former inferred type causes an error.

**Comment by subpardaemon** [comment] 2019-04-13 18:10
i have a completely unrelated occurrence but might be something of a common bug. when trying to build cucumber.ml ( https://github.com/cucumber/cucumber.ml ) they have an issue with the current master branch of having a deprecation warning, which becomes an error due to... overeagerness? anyways, i looked up how to make dune eat deprecation warnings, and the officially recommended way is to use the `dune build --profile release` switch. when i do, it starts spewing errors from *ocamlc*, namely:

``      ocamlc lib/.cucumber.objs/byte/cucumber__Docstring.{cmi,cmti} (exit 2)
(cd _build/default && /home/opam/.opam/4.07/bin/ocamlc.opt -w -40 -O3 -g -bin-annot -I lib/.cucumber.objs/byte -I /home/opam/.opam/4.07/lib/base -I /home/opam/.opam/4.07/lib/base/caml -I /home/opam/.opam/4.07/lib/base/shadow_stdlib -I /home/opam/.opam/4.07/lib/cmdliner -I /home/opam/.opam/4.07/lib/re -I /home/opam/.opam/4.07/lib/re/perl -I /home/opam/.opam/4.07/lib/seq -I /home/opam/.opam/4.07/lib/sexplib0 -no-alias-deps -open Cucumber__ -o lib/.cucumber.objs/byte/cucumber__Docstring.cmi -c -intf lib/docstring.mli)
/home/opam/.opam/4.07/bin/ocamlc.opt: unknown option '-O3'.
Usage: ocamlc <options> <files>
...``
i'm using 4.07 and opam 2.0.0, is it possible that dune is not in sync with the latest ocamlc?

**Comment by rgrinberg** [comment] 2019-04-14 06:45
I don't think so. `-O3` is an option that should be passed to ocamlopt and not ocamlc. In particular instead of `flags`, it should use `ocamlopt_flags`.

**Comment by subpardaemon** [comment] 2019-04-14 18:28
> I don't think so. `-O3` is an option that should be passed to ocamlopt and not ocamlc. In particular, instead of `flags`, it should use `ocamlopt_flags`.

so it's a bona fide issue?

**Comment by rgrinberg** [comment] 2019-04-15 08:31
Not with dune, but with the aforementioned package.

**Comment by rgrinberg** [comment] 2019-05-09 07:23
Closing as this is not a dune bug.

**Closed by rgrinberg** 2019-05-09 07:23 UTC
