### ISSUE TITLE
Invalid first line, expected: (lang <lang> <version>)

### ISSUE THREAD

**Issue by grayswandyr** [ocaml/dune#1552] opened 2018-11-19 13:11 UTC
Hi,

I don't know if this is on purpose but I'm surprised to see the following error as I wouldn't expect newlines to be meaningful in an s'expression. I haven't tested if this also happens with dune and dune-project files...
```
$ dune --version
1.5.1
$ cat dune-workspace 
(lang dune 1.0) (profile release)
$ dune utop
File "dune-workspace", line 1, characters 0-33:
1 | (lang dune 1.0) (profile release)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Invalid first line, expected: (lang <lang> <version>)
$ vi dune-workspace 
$ cat dune-workspace 
(lang dune 1.0) 
(profile release)
$ dune utop // OK
```
Thanks for the good work!

**Comment by diml** [comment] 2018-11-19 13:55
The idea is that the initial `(lang dune 1.0)` line controls not only the grammar of the configuration files, but also the lexical conventions. In particular, this will allow us to change the lexical conventions in the future without breaking backward compatibility.

**Comment by diml** [comment] 2018-11-19 16:29
It seems better to me to keep the first line separate.

This could indeed be made clearer in the manual and/or the error message could be improved.

**Comment by grayswandyr** [comment] 2018-11-19 20:02
Yeah I guess an improved error message is even better. I'll let you choose whether you want to close the issue or keep it open as a reminder.

**Comment by rgrinberg** [comment] 2018-11-20 04:56
It still seems like if we modify the lexical convention, we'll still be fairly whitespace insensitive. I think skipping leading whitespace/comments to parse the line is fine.

**Comment by diml** [comment] 2018-11-20 09:44
@rgrinberg is that so we can have a header in the file? I suppose that would be fine yes. However, that means that old dune binaries would not provide a good error message when invoked in a project where the first line of the `dune-project` file is not `(lang ...)`.

**Comment by rgrinberg** [comment] 2019-05-24 15:49
Adding headers would indeed be useful. Although for my use case it was just for trying to toggle between two `(lang ..)` lines with comments. I recall being annoyed that wasn't possible.

In any case, I'm closing this issue as the original complaint is not a bug and my feature request is so minor that I will never get around to it. Anyone who is keen on headers can complain and then make this improvement :)

**Closed by rgrinberg** 2019-05-24 15:49 UTC

**Comment by dra27** [comment] 2020-07-29 12:54
I hit this too (generating a `dune-project` file for a project which doesn't use Dune). FWIW, I would have expected _certainly_ to be allowed to put other things on the line after the `(lang dune)` and _possibly_ to be allowed to have whitespace and comments preceding it (although I can see sense in avoiding that).

In an utterly hypothetical and hellish parallel universe, imagine that Pineapple Inc. introduces a new platform cheeseOS which sensibly uses `\0` characters to represent line endings, viewing a text file as an array of C strings... you'd wish first "line" processing had strictly stopped at the `)` then! 😣😨🤪

**Comment by dra27** [comment] 2020-07-29 12:58
FWIW, this could be changed and be quite usable - @jeremiedimino is not quite correct in https://github.com/ocaml/dune/issues/1552#issuecomment-440209044, given that Dune displays the first line in the error message, so it's very quickly apparent that it's for a newer dune:

```
File "dune-project", line 1, characters 0-25:
1 | (lang dune 3.0)(name foo)
    ^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Invalid first line, expected: (lang <lang> <version>)
```

**Comment by jeremiedimino** [comment] 2020-07-29 14:13
That seems reasonable. No objection to relaxing a bit the parsing here.
