### ISSUE TITLE
Reusing the same modules for two different executable targets

### ISSUE THREAD

**Issue by XVilka** [ocaml/dune#1515] opened 2018-11-02 13:05 UTC
For example I have some set of *.ml and *.mli files, which can form either a distributed node, or a standalone tool (mostly for testing).
Lets say I have
 - tool_node.ml[i]
 - tool_standalone.ml[i]
 - some_file1.ml[i]
 - some_file2.ml[i]
 - some_file3.ml[i]

I want to build two executables - one is "tool_node + some_file1 + some_file2 + some_file3",
and another "tool_standalone + some_file1 + some_file2" (without "some_file3").

```
(executable
  (name tool_node)
  (preprocess (pps ppx_sexp_conv))
  (libraries base lwt something)
  (link_flags (-verbose -linkall))
  (modules (:standard \ tool_standalone)))

(executable
  (name tool_standalone)
  (preprocess (pps ppx_sexp_conv))
  (libraries base lwt something)
  (link_flags (-verbose -linkall))
  (modules tool_standalone))

(install
  (section bin)
  (files
	(tool_node.exe as tool_node)
	(tool_standalone.exe as tool_standalone)
  ))
```

But if I use `let somevar = Some_file2.some_func` (from "some_file2.ml" file) in the text of "tool_standalone.ml" - it complains about unbound module.
Would be nice to allow dune handle this case.

**Comment by nojb** [comment] 2018-11-02 13:16
The usual way to handle this is to make a `library` with the common parts (eg `Some_file1` and `Some_file2`) and use the library from both executables.

**Comment by rgrinberg** [comment] 2018-12-16 09:40
This is a duplicate of another issue and diml mentioned that we're not planning to change this.

**Closed by rgrinberg** 2018-12-16 09:40 UTC
