### ISSUE TITLE
No rule found for <file in dotted directory>

### ISSUE THREAD

**Issue by c-cube** [ocaml/dune#1407] opened 2018-10-05 18:03 UTC
Seems like dune doesn't know it should copy dependencies that are in a dotted directory (my use case is `.cargo/config` for vendoring stuff…)

[repro.tar.gz](https://github.com/ocaml/dune/files/2451629/repro.tar.gz)

```
tar cavf <repro.tar.gz>
cd foo/
dune exec main.exe # will fail
```

if you modify the `dune` file to use `bar` instead of `.foo/bar` it works.

**Comment by rgrinberg** [comment] 2018-10-05 18:14
From dune's perspective, this is expected behavior as dune will refuse the contents of any directory that starts with `.` or `_`. On the other hand, it's not something that the user can work around all the time. I wonder if we can have the user "unignore" directories explicitly to override the current behavior.

**Comment by diml** [comment] 2018-10-08 10:32
Basically there are two kinds of ignored sub-trees:

- ones that are considered as *raw data*, i.e. they can be used by the build but dune won't try to interpret `dune` files in such sub-trees. One consequence is that they will be scanned lazily
- ones that dune cannot see at all, such as `.git`, `_opam` or more generally any directory starting with `.` or `_`

It might be OK to change the status of the second kind to be the same as the first kind, but I'm not entirely sure. One issue thought is that we are currently using a few names such as `.ppx`, `_doc`, ... for internal purposes, so they'd be a clash if we allowed source directories to start with `.` or `_`.

**Comment by rgrinberg** [comment] 2018-11-06 20:46
This is actually a dupe of https://github.com/ocaml/dune/issues/185 and I proposed a way to solve this issue

**Closed by rgrinberg** 2018-11-06 20:46 UTC
