### ISSUE TITLE
Dependency cycle with include_dirs

### ISSUE THREAD

**Issue by crackcomm** [ocaml/dune#6491] opened 2022-11-16 16:19 UTC
## Expected Behavior

`include_dirs` in `foreign_stubs` stanza adds directories in `-I` compiler flags and also watches files for changes.

## Actual Behavior

In particular `(include_dirs %{project_root})` or including `.` (same with full path) creates a dependency cycle errors.

```
Error: Dependency cycle between:
   long-path/bigarray_utils/bigarray_utils_ml.o
-> required by
   long-path/bigarray_utils/libbigarray_utils_stubs.a
-> required by
   long-path/bigarray_utils/.bigarray_utils.inline-tests/inline_test_runner_bigarray_utils.exe
-> required by alias bigarray_utils/runtest in
   long-path/bigarray_utils/dune:6
```

The cycle is most likely infinite but blocked by some limits.

## Reproduction

- PR with a reproducing test: 

It should be easy to reproduce with this one line added to `foreign_stubs` stanza but I can help if that's a problem.

## Specifications

- Version of `dune` (output of `dune --version`): 3.2.0
- Version of `ocaml` (output of `ocamlc --version`): 4.14.0
- Operating system (distribution and version): Linux Mint 20.3

## Additional information 

It might be important to mention I'm using `esy` to run `dune`.

- Link to gist with verbose output (run `dune` with the `--verbose` flag):

Full output is just the above error repeated multiple times.

**Comment by crackcomm** [comment] 2022-12-20 07:08
It seems that the issue may be caused by bazel links in the workspace that are causing dune to traverse them indefinitely. Unfortunately, there is currently no option to make `data_only_dirs` recursive, which might be helpful in this situation.

**Comment by Alizter** [comment] 2023-03-11 21:45
I would like to write a test to reproduce this, have you got any more information about how to trigger it?

**Comment by crackcomm** [comment] 2023-03-11 22:27
I am not sure at the moment. I believe those were links created by bazel.

**Comment by emillon** [comment] 2023-10-17 12:43
Given that we can't reproduce the issue, I'm closing it. Please reopen if you can provide a reproduction case.

**Closed by emillon** 2023-10-17 12:43 UTC
Labels: bug
