### ISSUE TITLE
dune runtest inline tests: error with deps "glob_files_rec"

### ISSUE THREAD

**Issue by JoAllg** [ocaml/dune#5157] opened 2021-11-12 17:32 UTC
## Expected Behavior
It should be possible to define (inline_tests) dependencies with `glob_files_rec`

## Actual Behavior
While usage of `(deps (glob_files <glob>))` is accepted, `(deps (glob_files_rec <glob>))` throws the error "Unexpected list"

## Reproduction

1.  Full Dune file:
```
(library
 (name test)
 (libraries ) ;
 (inline_tests (deps (glob_files_rec ./*.tz))) ;
 (preprocess
  (pps ppx_jane)))
```
2. run "dune runtest"

## Specifications

- Version of `dune`: 2.9.1
- Version of `ocaml`: 4.13.1
- Operating system: Ubuntu 20.04 (WSL)

## Additional information 

- Link to gist with verbose output (run `dune` with the `--verbose` flag):
https://gist.github.com/JoAllg/bfef142b1f9e6081c2a63a1a34d0063c

**Comment by Alizter** [comment] 2021-11-17 02:10
I can confirm that this is a bug with 2.9.1 it seems. When on a newer version, setting the dune-project file to 2.9 lets you use glob_files_rec.

**Comment by ejgallego** [comment] 2021-11-17 16:21
The example you provide seems to work fine in `main`

**Comment by jeremiedimino** [comment] 2021-11-17 16:28
we looked at this in today's meeting: it is a bug in the manual and the parser: `glob_files_rec` is supported since 3.0.

**Comment by ejgallego** [comment] 2021-11-17 16:38
> I can confirm that this is a bug with 2.9.1 it seems. When on a newer version, setting the dune-project file to 2.9 lets you use glob_files_rec.

Indeed sorry for this bug and sorry for me pointing out incorrect info, glob_files_rec is 3.0 - only, we have now fixed Dune's main so it will require dune lang 3.0

**Comment by JoAllg** [comment] 2021-11-17 19:41
I'm glad this could be solved/clarified. Thanks.

**Closed** 2021-11-19 12:25 UTC
Labels: bug, acknowledged
