### ISSUE TITLE
dune subst dirty

### ISSUE THREAD

**Issue by Pitometsu** [ocaml/dune#2348] opened 2019-07-02 18:09 UTC
If I have dirty git repo, where several files removed, and run `dune subst`, I get
```
Error: exception Sys_error("removed-file-name: No such file or directory")
Backtrace:
Raised by primitive operation at file "pervasives.ml", line 385, characters 28-54
Called from file "src/stdune/io.ml", line 74, characters 17-37
Called from file "src/stdune/io.ml" (inlined), line 94, characters 29-64
Called from file "src/watermarks.ml", line 154, characters 10-27
Called from file "list.ml", line 85, characters 12-15
Called from file "src/fiber/fiber.ml", line 201, characters 18-23
Called from file "src/fiber/fiber.ml", line 99, characters 6-13

I must not segfault.  Uncertainty is the mind-killer.  Exceptions are
the little-death that brings total obliteration.  I will fully express
my cases.  Execution will pass over me and through me.  And when it
has gone past, I will unwind the stack along its path.  Where the
cases are handled there will be nothing.  Only I will remain.
```

Is it expected behaviour. How it intended to be used in such case?

**Comment by sim642** [comment] 2022-07-17 07:46
I encountered a related issue: in a git repo, where a file was added, but not yet committed, `dune subst` silently just didn't do substitutions in that file.

Looks like `dune subst` tries to work on git committed files, not what's actually present in the workspace, but that's nowhere mentioned, so it's rather confusing why it would even try to do something git-specific.

**Comment by emillon** [comment] 2022-07-26 14:04
> Is it expected behaviour

The `uncertainty is the mind-killer` message is never expected behavior. So that was not intended. However, it seems that it has been fixed and we now fail with "Error: file does not exist" which seems fine to me.

> Looks like dune subst tries to work on git committed files, not what's actually present in the workspace

That is correct. The canonical example is when a package is pinned by opam to a git version. It relies on the vcs info, I'll document this. As a consequence, `dune subst` does nothing when no vcs is detected.

**Closed** 2022-08-01 07:36 UTC
