### ISSUE TITLE
internal error: module not found in dependency graph

### ISSUE THREAD

**Issue by avsm** [ocaml/dune#325] opened 2017-11-12 14:18 UTC
```
$ jbuilder build
Internal error, please report upstream including the contents of _build/log.
Description: "Obi" not found in map <dependency graph in _build/default/obi/lib>
Backtrace:
Raised at file "src/import.ml", line 19, characters 43-65
Called from file "src/top_closure.ml", line 24, characters 24-44
Called from file "src/top_closure.ml", line 33, characters 14-42
Called from file "src/top_closure.ml", line 37, characters 10-58
Called from file "src/ocamldep.ml", line 94, characters 8-54
Called from file "src/ocamldep.ml", line 102, characters 11-45
Called from file "src/build_system.ml", line 272, characters 16-33
Called from file "src/build_system.ml", line 259, characters 8-25
Called from file "src/build_system.ml", line 259, characters 8-25
Called from file "src/build_system.ml", line 259, characters 8-25
Called from file "src/build_system.ml", line 259, characters 8-25
Called from file "src/build_system.ml", line 306, characters 17-47
Called from file "src/future.ml", line 88, characters 40-45
Called from file "src/future.ml", line 93, characters 8-12
speck:obi avsm$ more _build/log 
# jbuilder build
# OCAMLPARAM: unset
# Workspace root: /Users/avsm/src/working/obi
$ /Users/avsm/.opam/4.05.0/bin/ocamlfind printconf path > /var/folders/pc/5d4q7zyj4wl8lcdr1v1gmq7r0000gn/T/jbuild357452.output
$ /Users/avsm/.opam/4.05.0/bin/ocamlc.opt -config > /var/folders/pc/5d4q7zyj4wl8lcdr1v1gmq7r0000gn/T/jbuildc5dc44.output
# Jbuilder context:
#  ((name default)
#   (kind default)
#   (merlin true)
#   (for_host ())
#   (build_dir _build/default)
#   (toplevel_path (/Users/avsm/.opam/4.05.0/lib/toplevel))
#   (ocaml_bin /Users/avsm/.opam/4.05.0/bin)
#   (ocaml /Users/avsm/.opam/4.05.0/bin/ocaml)
#   (ocamlc /Users/avsm/.opam/4.05.0/bin/ocamlc.opt)
#   (ocamlopt (/Users/avsm/.opam/4.05.0/bin/ocamlopt.opt))
#   (ocamldep /Users/avsm/.opam/4.05.0/bin/ocamldep.opt)
#   (ocamlmklib /Users/avsm/.opam/4.05.0/bin/ocamlmklib.opt)
#   (env ())
#   (findlib_path (/Users/avsm/.opam/4.05.0/lib))
#   (arch_sixtyfour true)
#   (natdynlink_supported true)
#   (opam_vars ())
#   (ocamlc_config
#    ((architecture amd64)
#     (asm "clang -arch x86_64 -c")
#     (asm_cfi_supported true)
#     (ast_impl_magic_number Caml1999M020)
#     (ast_intf_magic_number Caml1999N018)
#     (bytecomp_c_compiler
#      "gcc  -O2 -fno-strict-aliasing -fwrapv -D_FILE_OFFSET_BITS=64 -D_REENTRANT ")
#     (bytecomp_c_libraries "-lcurses -lpthread                  ")
#     (cc_profile -pg)
#     (ccomp_type cc)
#     (cma_magic_number Caml1999A012)
#     (cmi_magic_number Caml1999I021)
#     (cmo_magic_number Caml1999O011)
#     (cmt_magic_number Caml2012T009)
#     (cmx_magic_number Caml1999Y015)
#     (cmxa_magic_number Caml1999Z014)
#     (cmxs_magic_number Caml2007D002)
#     (default_executable_name a.out)
#     (exec_magic_number Caml1999X011)
#     (ext_asm .s)
#     (ext_dll .so)
#     (ext_exe "")
#     (ext_lib .a)
#     (ext_obj .o)
#     (flambda false)
#     (host x86_64-apple-darwin16.7.0)
#     (int_size 63)
#     (model default)
#     (native_c_compiler
#      "gcc  -O2 -fno-strict-aliasing -fwrapv -D_FILE_OFFSET_BITS=64 -D_REENTRANT")
#     (native_c_libraries "")
#     (native_pack_linker "ld -r -arch x86_64  -o ")
#     (os_type Unix)
#     (profiling true)
#     (ranlib ranlib)
#     (safe_string false)
#     (spacetime false)
#     (standard_library /Users/avsm/.opam/4.05.0/lib/ocaml)
#     (standard_library_default /Users/avsm/.opam/4.05.0/lib/ocaml)
#     (standard_runtime /Users/avsm/.opam/4.05.0/bin/ocamlrun)
#     (system macosx)
#     (systhread_supported true)
#     (target x86_64-apple-darwin16.7.0)
#     (version 4.05.0)
#     (with_frame_pointers false)
#     (word_size 64)))
#   (which
#    ((ocamlc (/Users/avsm/.opam/4.05.0/bin/ocamlc.opt))
#     (ocamlfind (/Users/avsm/.opam/4.05.0/bin/ocamlfind)))))
$ jbuilder --version
1.0+beta16
```

**Comment by avsm** [comment] 2017-11-12 14:27
having difficulty reproducing, but this was in a multi-repo workspace with some symlinks to the upstream repos...

**Comment by rgrinberg** [comment] 2018-03-22 06:26
Closing this because this code path is quite different now and the stack trace isn't really applicable. Please let us know if you're able to reproduce this again.

**Closed by rgrinberg** 2018-03-22 06:26 UTC
