### ISSUE TITLE
[FEATURE REQUEST] running an alternative toplevel to utop

### ISSUE THREAD

**Issue by progman1** [ocaml/dune#4147] opened 2021-01-22 11:21 UTC
## Desired Behavior

running 'dune utop' supplies that toplevel with the required orchestration of libraries
and include paths for a seamless experience.
it would be useful to do the same for any designated toplevel.

## Example

ie. one that was modified to accept a driver script as a preamble to interactive use
and/or integrates libraries outside the current project.

## Existing?

[dune top] gives the means to orchestrate local libraries but 
 generates the info only when run from within the source directory.
it doesn't appear possible to chdir to this directory from within a rule
despite the documentation on the variable ```%{project_root}``` indicating
it to be the dune-project homed directory - on my system workspace_root and
project_root are both _build/default.  which is correct?
Without ability to chdir to the source my get around is to have a Makefile
in the source directory launching a custom toplevel on a script that has a
```#use_output``` directive.

**Comment by jeremiedimino** [comment] 2021-01-27 16:34
Do I understand correctly that you want to call `dune top` from inside a `dune` file?

**Comment by ejgallego** [comment] 2021-01-27 16:36
I'd guess a thing that would help here is a way to better extract some of the flags that are passed to the toplevels, for example a way to have `%{flags:foo_lib:include}` so you could add them to a rule, and would actually add the dependency on `foo_lib`'s include files.

**Comment by jeremiedimino** [comment] 2021-01-27 17:23
That would be nice indeed

**Comment by progman1** [comment] 2021-02-02 01:55
yes, to use 'dune top' from a dune rule.
the show stopper seems to be trying to use project_root/workspace_root to get back to the source directory and getting an error message about leaving the scope of the workspace.

**Comment by jeremiedimino** [comment] 2021-02-02 09:57
Ack.

There is indeed no way to go back to the source directory. Conceptually, the build works on a copy of the source tree extended with build artifacts. So referring to the source tree explicitly could be a bit awkward.

Dune errors out when leaving the scope of the workspace because the build directory is not fixed. For instance, if the user passes `--build-dir /tmp/build`, then `%{workspace_root}/../../` will definitely not be the source tree.

To do what you are trying to do, you also need to make sure there is no parallelism and the command has direct access to the terminal. i.e. you need to run dune with `dune build -j 1 --no-buffer`. It also seem to me that it would be better if Dune completely handed over the execution to such a command rather than wait for it to finish and continue the build. Finally, running `dune` inside `dune` has some limitations as well.

Have you tried the [toplevel stanza](https://dune.readthedocs.io/en/latest/dune-files.html#toplevel) BTW? It was designed for this.

**Comment by progman1** [comment] 2021-02-10 04:15
> Have you tried the toplevel stanza BTW? It was designed for this.

in my case the toplevel is a slightly modified set of compiler sources
so this doesn't apply.
and  given your prior observations I will make do with Make as a final invocation step then.
thanks!

**Comment by jeremiedimino** [comment] 2021-02-10 09:25
That seem reasonable. Closing this then.

**Closed by jeremiedimino** 2021-02-10 09:25 UTC
