### ISSUE TITLE
Target inference for stanzas `rule` in long form should not be allowed if dune lang < 2.0.0

### ISSUE THREAD

**Issue by voodoos** [ocaml/dune#3748] opened 2020-08-27 12:16 UTC
## Reproduction:
- A `dune-project file` with `lang dune < 2.0.0`
- A dune file with a stanza `rule` in long form without explicit targets:
```lisp
(rule
  (action (copy# some_file.ml.%s some_file.ml)))
```
(note that this is indeed the long form, short would be `(rule (copy# some_file.ml.%s some_file.ml))`) 

## Expected Behavior
Latest Dune should refuse to build the project because target inference for the long forms of the stanza `rule` was introduced in version 2.0.0 of the dune language (#2494, fixes #2469).

## Actual Behavior
Latest Dune builds the project without complaining.

## Specifications

- Version of `dune`: 2.7.0 (but probably all versions >= 2.0.0 are affected)
- Version of `ocaml`: 4.11.0
- Operating system: MacOS Catalina

## Other
See https://github.com/ocaml/merlin/issues/1157

**Comment by emillon** [comment] 2020-08-31 09:42
Duplicate of #3230

**Closed** 2020-08-31 09:57 UTC
