### ISSUE TITLE
dune install and file permissions

### ISSUE THREAD

**Issue by maroneze** [ocaml/dune#5995] opened 2022-07-21 12:01 UTC
## Expected Behavior

`dune install` should maintain file permissions (read, write, execute), or explicitly document that they are normalized.
For instance, files installed to section `share` have their permission normalized (apparently to 0644) independently of their original permission (e.g. a read-only file becomes writable; an executable file loses its execution bit; files only readable to the current user become readable to group/others).

The [install](https://dune.readthedocs.io/en/stable/dune-files.html#install) stanza documentation does mention the following:

> - `libexec` installs by default to `<prefix>/lib/<pkgname>/` **with the executable bit set**
> - `libexec_root` installs by default to `<prefix>/lib/` **with the executable bit set**
> - `bin` installs by default to `<prefix>/bin/` **with the executable bit set**
> - `sbin` installs by default to `<prefix>/sbin/` **with the executable bit set**
> ...
> - `stublibs` installs by default to `<prefix>/lib/stublibs/` **with the executable bit set**

But without explicitly mentioning that all other sections will have the executable bit unset.

Also, no mention is made concerning the read/write bits.

`dune install --help` also contains no mention whatsoever concerning permissions.

I could not find any flags/options to modify this behavior.

## Actual Behavior

Files lose their original permission information when installed.

## Reproduction

1. `dune init project proj`
1. `cd proj`
1. `touch readonly && chmod -w readonly`
1. `touch exec.sh && chmod +x exec.sh`
1. `touch private && chmod 400 private`
1. `echo "(install (section share) (files readonly exec.sh private))` > dune
1. `dune build`
1. `dune install --prefix $PWD/build`

The files `readonly`, `exec.sh` and `private` in `build/share/proj` all have permissions 0644.

Note that, during build (inside `_build/default`), the copied files lose their write permission, but maintain otherwise their read/execute bits.

## Specifications

- Version of `dune` (output of `dune --version`): 3.3.1
- Version of `ocaml` (output of `ocamlc --version`) 4.08.1
- Operating system (distribution and version): Linux Fedora 36

**Comment by emillon** [comment] 2022-07-22 10:27
Indeed, that's intended behavior: everything is either installed as `0o755` or `0o644`. I'll document it as such. Thanks!

**Comment by maroneze** [comment] 2022-07-22 11:34
Thanks for the clarification.

Is a modification of this behavior a possible feature that could be implemented someday? For instance, instead of writing:

```
(install (section share) (files readonly exec.sh private))
```

One would write:

```
(install (section share) (files (with-chmod 0o444 readonly) (with-chmod 0o755 exec.sh) (with-chmod 0o400 private)))
```

To obtain a more configurable behavior. Otherwise we will need substantial changes to our code to conform to the current behavior.

As examples from other build systems, [CMake has PERMISSIONS](https://stackoverflow.com/questions/19399705/cmake-how-to-change-file-permissions-when-installing), [Ant has a chmod task](https://stackoverflow.com/questions/14962019/can-linux-file-permissions-be-modified-in-ant), [Meson has an install_mode](https://github.com/mesonbuild/meson/issues/2433), etc...

I understand that such changes take time, but in our case it might be worth trying to add such a feature to Dune rather than modifying our current setup to conform to the existing situation.

However, if there has already been some discussion on the subject, e.g. on why such features would not be doable (technical limitations or design principles), it would save us the time of trying to implement them.

**Comment by emillon** [comment] 2022-07-22 12:43
To give you some context: dune's install semantics come from opam. When defining an installable library `l`, the "end" target is a file named `l.install` which contains, in opam syntax, files and their sections. This file can be interpreted by `opam` at the end of a build, or directly by `dune install`.

But the mapping between `(install)` stanzas and what `dune install` does is not direct - everything is expressed in the install file. So to support that, the file format has to support that (and opam too).

If that's something you want, I'd encourage you to open a discussion [on the opam issue tracker](https://github.com/ocaml/opam/issues). You can find [the documentation of install files here](https://opam.ocaml.org/doc/Manual.html#lt-pkgname-gt-install). Note that it is a slightly unusual design: some sections install to the same directory, like `lib` and `libexec` (which has a different role from say `/usr/libexec`). Maybe you can suggest new sections that correspond to the behavior you want; or a completely new design with explicit directory and modes.

As for this issue, I'll close it with the docs improvement and you can open a feature request on dune once the design on the opam side has been implemented. Thanks!

**Comment by maroneze** [comment] 2022-07-22 12:51
Great explanation, thanks!

**Closed** 2022-07-22 12:51 UTC
Labels: docs

**Comment by emillon** [comment] 2022-07-26 08:31
It's slightly more complex than I explained: opam supports 2 kinds of "install" instructions. Either you write a `.install` file, or a `install:` command in the opam file. For the first one, you'll have to map to the existing sections, and modes will need to map to that. With the second one, you can do what you want because it's an arbitrary command. The first style has nice benefits, for example opam statically knows which files are installed by which package. Dune only supports the first style. But `frama-c` uses an explicit `install:` command.
