### ISSUE TITLE
Internal error in the S-expression parser, when parsing ELF header

### ISSUE THREAD

**Issue by ksromanov** [ocaml/dune#1987] opened 2019-03-28 22:46 UTC
Dune (version 1.8.2) can not parse `ELF` header; OS Linux/x86-64:
```
File "dune", line 1, characters 0-0:
Error: Internal error in the S-expression parser, please report upstream.
```

To reproduce, just copy `dune` executable to home directory and run `dune build`.

**Comment by nojb** [comment] 2019-03-29 09:19
I understand correctly that you put the `dune` *executable* in your current directory and called `dune build`, so that `dune` would try to parse the binary as if it were a build description file?

Not sure this is a sensible thing to do.

**Comment by jberdine** [comment] 2019-03-29 09:31
FWIW, I've seen this run into a number of times (with local opam switches, in CI scripts, etc.). Might be worth changing the error message if nothing else.

**Comment by ksromanov** [comment] 2019-03-29 13:05
@nojb - putting `dune` executable in the current directory is just a way to reproduce. The actual problem happens in situations described by @jberdine (thanks for comment!). `dune` asks to contact `upstream`, and so I do. ;-)

I actually don't see any reason not to contact, since `S-expression parser` is very generic thing, and authors may consider that it should gracefully handle ELF header, or at least not produce internal error. For instance, `ocamlopt` parser in the same situation writes

```
File "ocamlopt.ml", line 1, characters 0-1:
Error: Illegal character (\127)
```

But, of course, feel free to close the issue.

**Comment by emillon** [comment] 2019-03-29 15:23
Yes, just saying something like "./dune does not look like a dune configuration file" would solve this nicely I think.

**Comment by ksromanov** [comment] 2019-03-29 16:53
I played with `dune` - it actually produces internal error on any _non-printable_ character. For instance

```bash
$ echo -e "Nicol\xE1s Ojeda B\xE4r" > dune
$ dune build
File "dune", line 1, characters 5-5:
1 | Nicolás Ojeda Bär
         
Error: Internal error in the S-expression parser, please report upstream.
```

Actually there are 2 issues:

1. Internal error in S-expression parser, which might be interesting to the Author of the parser (Jérémie Dimino?). But it is not critical.

2. On linux systems in some setups `dune` executable can be interpreted as a config file. Workaround - ignore whole directory with local `dune` setup with `ignore_subdirs`.
Also not critical, but it would be nice to ignore such files automatically (Linux Elf magic number `"\x7FELF"`, Mac OSX has a different format with different magic number, Windows, hopefully has extension `.exe`, so there should be no conflict).

**Comment by diml** [comment] 2019-04-01 11:18
Yh, the error message is clearly terrible.

**Comment by diml** [comment] 2019-04-01 11:21
Using a generic error message as @emillon suggests seems good to me. Silently ignoring such files might cause more issues than it solves

**Comment by ksromanov** [comment] 2019-04-01 13:52
@diml - a hint to use `ignore_subdirs` in error message would be also helpful.

Should it stop on first failed parse (as of right now) or ignore it and search for other dune files? Currently locally installed dune breaks the build.

**Comment by emillon** [comment] 2019-04-01 14:04
How does your setup look like? `dune` is usually invoked in a source directory, not in the root of a large directory like `$HOME`, so this behaviour is usually not a problem (besides the error message that is not precise enough).

**Comment by ksromanov** [comment] 2019-04-01 14:57
The setup is quite exotic: the building tools and required libraries are installed in a subdirectory of a package source tree. Imagine, you git clone this repo and make a local OPAM switch inside it - i.e.

```
dune/
    .github
    .local-opam-switch
    bench
    ....
```

In my case it is not opam, but anyway, dune executable is reachable from root directory of the package. There is nothing critical, just some polishing will make such a great tool as `dune` even better.

**Comment by diml** [comment] 2019-04-01 15:46
I see, I didn't realise that this was caused by local opam switches. Is there an easy way to detect that a directory is a local opam switch? Alternatively, we could add a way to stop the recursion in dune via a special file and ask opam to generate this file.

**Comment by emillon** [comment] 2019-04-01 16:01
If that helps in the meantime, dune will ignore directories named `_opam`.

**Comment by ksromanov** [comment] 2019-04-01 16:12
In my case it is not opam switch - it is local dpkg installation. Also, as mentioned above, the same problem happens with CI setups. But the root of the problem is that dune project files are named `dune`.

May be it worth just replacing error message with a warning "File $path/dune does not look like dune project file. To ignore it, use ignore_subdirs command in top-level dune." and continue processing directories?

**Comment by rgrinberg** [comment] 2019-04-02 04:15
I think addressing the error message is the most we can do at this time. If you don't want to see it, use the `dirs` stanza (not `ignored_subdirs` as it's deprecated).

**Comment by diml** [comment] 2019-04-02 10:45
Wow, I didn't know it was possible to have a local dpkg installation. That seems neat.

I guess not having the configuration files called `dune` would avoid the issue, though it's still not great to have dune crawl such directories :/

BTW, thinking about this again, I'm surprised by this issue. By default dune ignores directories starting with a `.` or `_`. I just tried the following on my machine and it succeeded:

```
$ mkdir .local-opam-switch
$ echo x > .local-opam-switch/dune
$ dune build
```

**Comment by ksromanov** [comment] 2019-04-16 20:40
@diml 

Sorry, this is my misprint - of course, in our case the directory name is without leading dot. Thank you very much for the hint!

**Comment by diml** [comment] 2019-04-17 08:46
Ok. Is renaming the directory to start with a dot or underscore an acceptable solution in your case then?

**Comment by ksromanov** [comment] 2019-04-17 12:58
Yes, of course.

**Comment by diml** [comment] 2019-04-17 13:43
Ok, cool :)

Given that and the fact that we improved the error message, I propose to close this PR. Feel free to re-open if you experience more issues.

**Closed by diml** 2019-04-17 13:43 UTC
